### ISSUE TITLE
Make gitmoji-cli usable offline.

### ISSUE THREAD

**Issue by welcoMattic** [carloscuesta/gitmoji-cli#1]
It will be useful to make it works offline, as I work often in no-wifi train, I want to be able to commit without internet connection required.

**Comment by carloscuesta** [comment]
Yep @welcoMattic the request would be in a cache! don't worry for that 😜

**Comment by carloscuesta** [comment]
I'll keep this open as a "card" for that feature

**Comment by welcoMattic** [comment]
Ok 😉
