### ISSUE TITLE
/.git/index.lock: File exists

### ISSUE THREAD

**Issue by thinklife** [carloscuesta/gitmoji-cli#10]
? Choose a gitmoji: 🎨  - Improving structure / format of the code.
? Enter the commit title: add article
? Enter the commit message:
? Issue / PR reference #:
? Signed commit: Yes
ERROR: fatal: Unable to create  'xxxxxx/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

**Comment by carloscuesta** [comment]
Same as #9

**Comment by carloscuesta** [comment]
What OS are you using @thinklife ?

**Comment by thinklife** [comment]
macOs version: 10.12.1

**Comment by thinklife** [comment]
@carloscuesta 
macOs version: 10.12.1
iTerm2 + oh my zsh
