### ISSUE TITLE
Error when using -i option

### ISSUE THREAD

**Issue by GitSquared** [carloscuesta/gitmoji-cli#104]
Hello @carloscuesta! (nice issue template by the way, i might just steal it)

I can't seem to setup the gitmoji hook using `gitmoji-cli`.

Issue: 
- create a new git repo
- `cd` into the thing
- run `gitmoji -i`
- get error message below
- cry

**OS**: Debian 9
**gitmoji-cli -v**: 1.9.0
**Node version**: v9.11.1

**Error Message**: `ERROR: Error: ENOENT: no such file or directory, open '--absolute-git-dir/hooks/prepare-commit-msg'`

**Comment by carloscuesta** [comment]
Hey @GitSquared thanks for the report that might be related with #90 @CGA1123

**Comment by GitSquared** [comment]
@Keyzou thanks for the help. I'll try this when i get home.
