### ISSUE TITLE
Allow committing using the previously used message

### ISSUE THREAD

**Issue by segersniels** [carloscuesta/gitmoji-cli#1068]
### Description of the problem

When you are using precommit staged linting your commit gets rejected due to present linting errors. Which then results in having to first fix the linting error (if you don't want to use `--no-verify` obviously) and then rewriting the original message. Just basically a bad user experience.

### Solution

Allow tracking of the last used message through a configurable config value and let users call `gitmoji commit --previous` to use the last message. This would improve UX by a lot in cases where it is useful.

### Alternatives

https://github.com/segersniels/gitmoji

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue requesting the same feature.

**Comment by carloscuesta** [comment]
Hey!

This is currently possible, see https://github.com/carloscuesta/gitmoji-cli/issues/452
