### ISSUE TITLE
Introduce AI generated messages

### ISSUE THREAD

**Issue by segersniels** [carloscuesta/gitmoji-cli#1069]
### Description of the problem

Sometimes you find yourself unable to find a fitting commit message. 

### Solution

1. Utilising the OpenAI API `gitmoji` could generate fitting commit messages based on the diff of the staged changes.
2. Check for a configured `OPENAI_API_KEY`

### Alternatives

https://github.com/segersniels/gitmoji
https://genmoji.xyz

I added support to `@segersniels/gitmoji` based on my original implementation of `genmoji.xyz` through `gitmoji commit --generate` with the option to provide additional context `gitmoji commit --generate --context`.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue requesting the same feature.

**Comment by carloscuesta** [comment]
Hey!

Thanks for opening the issue, I believe it can be a great addition into the cli 😊 

I don't have a lot of time now so if you want to raise a Pull-Request I would be more than happy to review it 😊

**Comment by segersniels** [comment]
Closed the PR but keeping this issue open to see if people have general interest in a feature like this.
