### ISSUE TITLE
some emoji lose a space after itself

### ISSUE THREAD

**Issue by pan3793** [carloscuesta/gitmoji-cli#107]
i use unicode mode, just use: gitmoji -l
⬇️ ⬆️ ♻️ 🗃 🏗
those emoji are different with others, they lose a space between itself and - .

**Comment by carloscuesta** [comment]
That's the problem when using unicode instead of the `code` format, sometimes you get weird spacing issues @pan3793

**Comment by ABHIJEET-MUNESHWAR** [comment]
@carloscuesta Any solution to this bug?

**Comment by carloscuesta** [comment]
Not really @ABHIJEET-MUNESHWAR
