### ISSUE TITLE
Replace `inquirer` with `prompts`

### ISSUE THREAD

**Issue by segersniels** [carloscuesta/gitmoji-cli#1077]
### Description of the problem

It seems like `inquirer` still has issues with flickering prompts when typing which results in bad UX which it has been having for a very long time.

### Solution

Might have to check if viable to switch away from `inquirer` to something like `prompts` for better UX. 
From my own experiences `prompts` doesn't have this issue.

https://www.npmjs.com/package/prompts

### Additional context

See video for weird flickering issue in `inquirer`.

https://user-images.githubusercontent.com/10974647/236788387-4ff044dd-9096-40ca-bcfa-c613b0b73c78.mov

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue requesting the same feature.

**Comment by carloscuesta** [comment]
Hey! @segersniels thanks for opening the issue I believe it's a great idea

I'm happy to move away from inquirer if this library provides better UX for our users. I see they even have `autocomplete` support, so we should be able to fit this 1:1 ❤️

**Comment by segersniels** [comment]
Had a quick go at this. While it does provide better UX (read: less flickering) during gitmoji selection it does introduce a bunch of flickering during the title prompt due to the input transforming that takes place (showing capitalization and max title length count).

So not sure if worth the effort. Might look into some other alternatives when I find the time.

**Comment by segersniels** [comment]
Actually, I just noticed that the live version also flickers when typing during the title prompt. So there's not really a regression. Doesn't take away from the fact that transforming the title during typing slows down the rendering and causes the flickering as you can see in the first video posted.


https://github.com/carloscuesta/gitmoji-cli/assets/10974647/9ea1878c-1229-4aba-8726-c70c8640346e

**Comment by carloscuesta** [comment]
> Doesn't take away from the fact that transforming the title during typing slows down the rendering and causes the flickering as you can see in the first video posted where the mutation doesn't happen and there's no flickering (with prompts).

Yes, every transformation to the input will cause some flickering as the terminal needs to re-render that reacting to user input, so it will flicker no matter what dependency we use for the prompts.

Even though looks like in the auto select prompt the experience is a bit better (as there's no flickering at all)

**Comment by segersniels** [comment]
Closing this for the time being. Might revisit in the future as there's no complaints coming in from other people.
