### ISSUE TITLE
Add a prompt option for story_id

### ISSUE THREAD

**Issue by trixtur** [carloscuesta/gitmoji-cli#1094]
### Description of the problem

Many project management systems have github integrations. If we could prompt for story_id this would allow the story to be linked to each commit.

### Solution

Add the option during config to prompt for story id.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue requesting the same feature.

**Comment by trixtur** [comment]
I've attempted to support this. Some tests are not yet passing but it is close.

**Comment by trixtur** [comment]
Should be ready to go.

**Comment by carloscuesta** [comment]
Hey!

Have you considered as an alternative using the scope prompt or the title?

**Comment by trixtur** [comment]
Sure have!

I investigated tools for my team at work to generate commit messages that would prompt them for important items we require in commit messages. This tool fit the bill having a `scope`, `title` and `description`. The only element that was missing was a prompt for the `storyId`.

I have submitted a PR which allows this item to be enabled through the config.

**Comment by trixtur** [comment]
It would be great if I could get a review: https://github.com/carloscuesta/gitmoji-cli/pull/1095

**Comment by carloscuesta** [comment]
Hey!

Sorry If my previous message is not clear enough.

I was wondering if we really need this prompt at all when we already have the one for scope?

Also it's something you can include as part of the prompt title

**Comment by trixtur** [comment]
I understand. I preferred it as a separate commit message within its own `-m` set.

Is there a reason not to do this?

**Comment by carloscuesta** [comment]
> I understand. I preferred it as a separate commit message within its own `-m` set. In this way we can preserve the scope and title for human readable items.
> 
> Is there a reason not to do this?

Cognitive complexity mostly, the more questions/prompts we introduce inside of the cli,  the "complicated" and not so easy to use will be.

Btw, we use to have this prompt a few years ago in the cli (and got removed) see https://github.com/carloscuesta/gitmoji-cli/issues/44
