### ISSUE TITLE
Implement fuzzy search

### ISSUE THREAD

**Issue by winstonjz** [carloscuesta/gitmoji-cli#110]
Hello @carloscuesta!

I used the npm package fuzzy suggested inquirer-autocomplete-prompt on my fork to implement fuzzy search. Can I make a PR for this ? 
Issue: 

![fuzzy-gitmoji](https://user-images.githubusercontent.com/20022500/42719486-eaca4d62-86ca-11e8-8eb7-9fbb25a06dd6.gif)

**Comment by carloscuesta** [comment]
This is already implement at the cli see #33
