### ISSUE TITLE
Should autoAdd add all project files instead /path/ files?

### ISSUE THREAD

**Issue by NE-SmallTown** [carloscuesta/gitmoji-cli#113]
Issue:  From: 

https://github.com/carloscuesta/gitmoji-cli/blob/master/src/gitmoji.js#L150

It seems that we can only add the files of current path. But for a project, it would be better to add all files. E.g. use https://github.com/inxilpro/node-app-root-path instead `add .`

**OS**: MacOS
**gitmoji-cli -v**: 1.9.0
**Node version**:8.11.3

**Comment by carloscuesta** [comment]
Hey @NE-SmallTown 

I think it's easier and more straightforward to add files at the current path. That enforces you to have always open the project root directory.
