### ISSUE TITLE
error with "$running" in commit title

### ISSUE THREAD

**Issue by STRRL** [carloscuesta/gitmoji-cli#114]
hello, i think here is a bug with env variables.

i write this as commit title:

"use $running as String"

but after commit, it shows "use ½¬ as String".
then i run `echo $running`, nothing output.

**Comment by carloscuesta** [comment]
Works fine for me @STRRL maybe is something related with your shell

![screen shot 2018-09-08 at 23 51 48](https://user-images.githubusercontent.com/7629661/45258940-2fb1aa00-b3c2-11e8-9d2a-f03dd6430080.png)
