### ISSUE TITLE
Git hook scripts not showing in console

### ISSUE THREAD

**Issue by kykungz** [carloscuesta/gitmoji-cli#115]
Hello @carloscuesta!

I'm trying out with the new [vue-cli](https://github.com/vuejs/vue-cli), and installed the built-it git hook, which later I learned that it uses Evan You's [yorkie](https://github.com/yyx990803/yorkie) package. When I try to use `gitmoji -c`, the git hook scripts are running normally, but without logging on my console. However, when the git hook scripts found errors while running, it does show the errors on my console (in red text).

Issue: 

Git hook scripts running result is not shown in console (but errors are shown).

#### Normal commit
`$ git commit -m "Trying to commit"`
```bash
> running pre-commit hook: lint-staged
 ↓ Running tasks for *.js [skipped]
   → No staged files match *.js
 ↓ Running tasks for *.vue [skipped]
   → No staged files match *.vue
[master 1b9858b] asdf
 2 files changed, 2 insertions(+), 1 deletion(-)
```
#### Gitmoji's commit

`$ gitmoji -c`
```bash
? Choose a gitmoji: 🎨  - Improving structure / format of the code.
? Enter the commit title [4/48]: test
? Enter the commit message:
? Issue / PR reference:
[master b991222] :art: test
 2 files changed, 3 insertions(+)
```
But I wanted to see this part
```bash
> running pre-commit hook: lint-staged
 ↓ Running tasks for *.js [skipped]
   → No staged files match *.js
 ↓ Running tasks for *.vue [skipped]
   → No staged files match *.vue
```

**OS**: macOS High Sierra 10.13.6
**gitmoji-cli -v**: 1.9.0
**Node version**: v9.11.2

**Error Message**:

**Comment by carloscuesta** [comment]
Hey @kykungz thanks for the suggestion I'm not considering doing this now!

**Comment by marcinlesek** [comment]
@carloscuesta any updates on it? 🤔was it considered to be developed?

**Comment by kylepeeler** [comment]
This would be a great improvement, I rely on seeing the output of my checks, and I get a really nasty error message when my git hook fails.
