### ISSUE TITLE
commit-hook not working

### ISSUE THREAD

**Issue by dcastil** [carloscuesta/gitmoji-cli#116]
Hello @carloscuesta!

The commit-hook applied with

```bash
$ gitmoji -i
```

doesn't work on my computer. When commiting, the gitmoji CLI appears as it should, but afterwards vim gets displayed and the terminal asks me for a commit message, which probably shouldn't be the case. When I close vim, I get the error message `Aborting commit due to empty commit message.` although I've provided a commit title through the gitmoji-cli.

Issue: 
Happens on each type of commit.

**OS**: Mac OS High Sierra 10.13.6
**gitmoji-cli -v**: 1.9.0
**Node version**: 8.10.0

**Error Message**: 

<img width="710" alt="screen shot 2018-08-08 at 15 40 03" src="https://user-images.githubusercontent.com/31006608/43840597-58bdec9c-9b21-11e8-9dc2-cac855555a20.png">

**Comment by carloscuesta** [comment]
I have no problems while using the commit hook @dcastil 🤔 

<img width="531" alt="screen shot 2018-08-08 at 16 16 09" src="https://user-images.githubusercontent.com/7629661/43842849-816f5630-9b26-11e8-9bb6-c1520c8d5d30.png">

**Comment by dcastil** [comment]
I just found out that the behaviour changes when I uninstall [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh). Then the title is displayed correctly in the edit message.

**Comment by carloscuesta** [comment]
I use zsh and have no problem. Then should be something related with your environment
