### ISSUE TITLE
windows terminal emoji display error

### ISSUE THREAD

**Issue by ko-yuki** [carloscuesta/gitmoji-cli#1182]
### Describe the bug

`gitmoji -l`, emoji display error when i use windows terminal
`gitmoji -v 5.0.2    node -v 14.11.0   windows 10 version 22h2`
![Dingtalk_20230825112344](https://github.com/carloscuesta/gitmoji-cli/assets/88355388/96f34b4d-44e6-4f83-80be-43f0bff2b578)

### Reproduction

null

### System Info

```Shell
`System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz
    Memory: 6.30 GB / 15.79 GB
  Binaries:
    Node: 14.11.0 - D:\dev-tools\node\node.EXE
    Yarn: 1.22.19 - D:\dev-tools\npm\global\yarn.CMD
    npm: 6.14.8 - D:\dev-tools\node\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.19041.1566`
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by carloscuesta** [comment]
Hey! Sorry that I'm not able to help much here

Perhaps you can find more info in these issues:

#488 https://github.com/carloscuesta/gitmoji-cli/issues/581

Thanks!
