### ISSUE TITLE
Regarding of Windows' hook issue

### ISSUE THREAD

**Issue by tsanyqudsi** [carloscuesta/gitmoji-cli#1235]
### Describe the bug

in Windows, there's a problem when using gitmoji-cli hooks as explained in https://github.com/carloscuesta/gitmoji-cli/issues/93.

Most probably it has nothing to do with gitmoji-cli but it has something to do with git bash. 

When I'm using VSCode, using gitmoji -c will switch the pwsh terminal to node terminal
![image](https://github.com/carloscuesta/gitmoji-cli/assets/1050880/a4365e82-4dc3-449f-ac3b-5d85ce21148e)

But when I use the hook, it will switch to git terminal instead

![image](https://github.com/carloscuesta/gitmoji-cli/assets/1050880/cdeaaf38-881a-4574-b319-1ba4586aa8c3)

### Reproduction

Use gitmoji hook in VSCode

### System Info

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 6.65 GB / 15.93 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.22621.1
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tsanyqudsi** [comment]
@carloscuesta could you put a warning in the readme file for this ?

**Comment by carloscuesta** [comment]
Hey!

Not sure 100% how VSCode renders that text, but to me looks like the text you refer as "terminal" is the name of the current active process, therefore it is correct that when you commit through `gitmoji-cli` it is display as `node` since we use a node process underneath.

Definitely not a bug
