### ISSUE TITLE
A filter to replace gitmoji code to gitmoji character and replace gitmoji character to gitmoji code

### ISSUE THREAD

**Issue by Freed-Wu** [carloscuesta/gitmoji-cli#1246]
### Description of the problem

When we `git log --oneline`, we will see:

```
725f254 :bug: Calculate check sum finally
4ec0b07 :technologist: Add receive_and_drop()
6c09fdd :technologist: Add loop for receive_data_frames()
76abe04 :technologist: Add send_and_receive_frame()
06ea47f :art: Move alloc outside loop
a4c27bc :alembic: receive data frames again
```

I hope gitmoji can provide a command line option to allow user:

```sh
git log --oneline | gitmoji --replace-gitmoji-code-to-gitmoji-character
```

Then we will get:

```
725f254 🐛 Calculate check sum finally
4ec0b07 🧑‍💻 Add receive_and_drop()
6c09fdd 🧑‍💻 Add loop for receive_data_frames()
76abe04 🧑‍💻 Add send_and_receive_frame()
06ea47f 🎨 Move alloc outside loop
a4c27bc ⚗️ receive data frames again
4d978e0 🧑‍💻 Add count_unreceived_data_frames()
```

### Solution

Just replace some characters. It should be very simple!

### Alternatives

Don't support it. User must see `:bug:` not :bug:.ZZ

### Additional context

![Screenshot from 2024-01-04 23-39-21](https://github.com/carloscuesta/gitmoji-cli/assets/32936898/0cfba395-fc0f-475c-979e-441ffdcc79d3)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue requesting the same feature.

**Comment by carloscuesta** [comment]
Hey!

Thanks for opening such a detailed issue, I think it would add a lot of value to the `cli` do you want to take stab into implementing this?

Thanks 😊

**Comment by Freed-Wu** [comment]
I am not sure which option name you want? `--replace-gitmoji-code-to-gitmoji-character` looks too long

**Comment by segersniels** [comment]
Not sure if this is something that should be handled by gitmoji if I'm completely honest. Sounds like a very small amount of people would benefit from this. I don't know of any but it would seem very unlikely to me if tools aren't available already that do exactly what you're asking for.

**Comment by Freed-Wu** [comment]
IMO, gitmoji generates these git commit message containing gitmoji code, so it is fair that it should provide some method to allow user to see these gitmoji character in `git log`.

**Comment by segersniels** [comment]
> IMO, gitmoji generates these git commit message containing gitmoji code, so it is fair that it should provide some method to allow user to see these gitmoji character in `git log`.

At that point wouldn't it make more sense to configure `gitmoji` to use the emoji format instead of the code format?

**Comment by Freed-Wu** [comment]
There are many git repo have used gitmoji to generate git commit message. Change their commit messages from code format to emoji format is impossible.

**Comment by segersniels** [comment]
@Freed-Wu In that case something like `emojify` should be sufficient for what you're looking for. https://github.com/mrowa44/emojify

**Comment by Freed-Wu** [comment]
I try and find emojify miss some gitmoji code:

![Screenshot from 2024-01-08 21-00-02](https://github.com/carloscuesta/gitmoji-cli/assets/32936898/2f6792dc-e8bb-42f0-94d3-743a92afbe95)

I think it should be the bug of emojify so I'll report it to them.
