### ISSUE TITLE
Allow backticks (`) in commit messages

### ISSUE THREAD

**Issue by ETLaurent** [carloscuesta/gitmoji-cli#126]
Hi!

It would be good to allow backticks in commit messages, to talk about code etc.

What do you think @carloscuesta ?

Cf. https://github.com/carloscuesta/gitmoji-cli/blob/460b79497ae7e791bc8ba8475bda8f0b93630dd3/src/guard.js#L14

**Comment by carloscuesta** [comment]
Hey @ETLaurent see #80

**Comment by ETLaurent** [comment]
@carloscuesta Ok my bad, I haven't looked very far.

And actually, backslashing backticks includes them in the commit.
