### ISSUE TITLE
unknown write failure on standard output

### ISSUE THREAD

**Issue by CitrusSoda** [carloscuesta/gitmoji-cli#1278]
### Describe the bug

![image](https://github.com/carloscuesta/gitmoji-cli/assets/49199024/ef2c30ad-0068-4f73-b252-7af635de0e96)

When I execute the command `gitmoji -c`, I encounter the error 'fatal: unknown write failure on standard output'. 
This issue occurs across different terminals including Powershell, git-bash, and cmd, even when I run them with admin.

Despite this, when I examine the git log, everything appears normal, and commits are successfully pushed to the remote repository without any issues.

```
gitmoji -v
9.1.0
```

### Reproduction

`gitmoji -c`

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 7800X3D 8-Core Processor
    Memory: 23.55 GB / 31.12 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.4.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.19041.3636
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by segersniels** [comment]
Does it only happen when committing through `gitmoji` or can you replicate by just running a manual `git commit -m "..."`? This feels more like a Windows issue than a `gitmoji` issue.

**Comment by CitrusSoda** [comment]
> Does it only happen when committing through `gitmoji` or can you replicate by just running a manual `git commit -m "..."`?

I do not encounter any issues when committing a manual git commit -m '...'. 
The problem only occurs when I use gitmoji -c.

**Comment by CitrusSoda** [comment]
Sorry, only sometimes seems to conflict with my original language in GitHub commit.
I'll close the issue. 

Thank you for making a good project!
