### ISSUE TITLE
gitmoji -c throws ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by enorfelt** [carloscuesta/gitmoji-cli#1321]
### Describe the bug

When issuing `gitmoji -c` bellow error is thrown:

node:internal/modules/esm/resolve:265
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\some.user\AppData\Roaming\nvm\v20.15.0\node_modules\gitmoji-cli\node_modules\inquirer\lib\prompts\base.js' imported from C:\Users\some.user\AppData\Roaming\nvm\v20.15.0\node_modules\gitmoji-cli\node_modules\inquirer-autocomplete-prompt\index.js
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:227:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///C:/Users/some.user/AppData/Roaming/nvm/v20.15.0/node_modules/gitmoji-cli/node_modules/inquirer/lib/prompts/base.js'
}

Node.js v20.15.0

### Reproduction

1. Open up a windows terminal using PowerShell Core
2. npm i -g gitmoji-cli
3. Restared windows terminal
4. do: gitmoji -c

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 12.32 GB / 31.72 GB
  Binaries:
    Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.81)
    Internet Explorer: 11.0.19041.4355
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by segersniels** [comment]
Can reproduce, seems like a `dependabot` bump of one of our packages broke. Will investigate.

**Comment by segersniels** [comment]
I made a PR to limit to minor versions of `inquirer` for now @carloscuesta 

https://github.com/carloscuesta/gitmoji-cli/pull/1322

**Comment by carloscuesta** [comment]
Released thanks everyone! ❤️

**Comment by enorfelt** [comment]
And it works! Thanks for the quick fix @segersniels  and @carloscuesta ❤
