### ISSUE TITLE
Add an option to enter scope of changes in a commit

### ISSUE THREAD

**Issue by rishichawda** [carloscuesta/gitmoji-cli#138]
Hello @carloscuesta!

Recently, folks at our organization shifted from [Commitizen](https://github.com/commitizen/cz-cli) to gitmoji-cli for commits for more readable commit messages and also because it just looks better! 
But we had one minor problem, _i must say feature request_, on the gitmoji cli. It would be better if we had an option to add `scope` to the commit message which helps us a lot in finding commits related to specific changes or when we want to see what changes were made in specific parts of our code base. 

Issue: 
No `scope` option makes it difficult to understand which parts of the entire repository / code base has changed. For example, if there are two different parts ( let's say, two Reactjs components or two different templates in a python django project, or two different kinds of services and/or independent or dependent parts of an application, etc ) which might have similar changes but on different commits, we can have same commit messages but with additional scope information which could be easier to read. This is not available currently on gitmoji-cli.

Something like this : 
![gitmoji](https://user-images.githubusercontent.com/26366288/47645446-142f7800-db97-11e8-9221-14e26450b821.png)

**Comment by rishichawda** [comment]
I'll raise a PR shortly for the demo of the feature. I've forked the repo and added the feature. Just working on the tests.

**Comment by rishichawda** [comment]
I'll raise a PR shortly for the demo of the feature. I've forked the repo and added the feature. Just working on the tests.

**Comment by rishichawda** [comment]
Raised a PR ( #139 ). Please review and add it as a feature to gitmoji-cli! Thanks!

**Comment by DoubleU23** [comment]
working on it!*

see #145 -> TBD

**Comment by carloscuesta** [comment]
Just reviewed the PR @rishichawda sorry for the late response 😊

**Comment by rishichawda** [comment]
Sorry I was on a vacation and hadn't checked my notifications. I'm glad that you took out your time and updated the PR. Thanks @carloscuesta!
