### ISSUE TITLE
Consider using unicode instead of :emoji:

### ISSUE THREAD

**Issue by carloscuesta** [carloscuesta/gitmoji-cli#14]
**Consider using unicode instead of :emoji:**

[Referring to that issue](https://github.com/carloscuesta/gitmoji/issues/60)

Changes that needs to be made to use unicode instead of :emoji:

```diff
{
	choices: gitmojis.map(gitmoji => {
		return {
			name: `${gitmoji.emoji}  - ${gitmoji.description}`,
+			value: gitmoji.code
		};
	})
}
{
	choices: gitmojis.map(gitmoji => {
		return {
			name: `${gitmoji.emoji}  - ${gitmoji.description}`,
-			value: gitmoji.emoji
		};
	})
}
```

**Comment by posva** [comment]
For those wanting to apply the local change, the file that needs to be modified is `src/gitmoji.js`

**Comment by posva** [comment]
Hey, what about having this option and maybe more in the future in some config (I'd rather add it to the packaged) using something like [cosmiconfig](https://github.com/davidtheclark/cosmiconfig)
Other possible options is omitting questions like the sign commit question

**Comment by carloscuesta** [comment]
Will take a look at cosmiconfig @posva 👍
