### ISSUE TITLE
what's your zsh theme? so good.

### ISSUE THREAD

**Issue by JJZHK** [carloscuesta/gitmoji-cli#143]
could you tell me what's your zsh theme?

**Comment by carloscuesta** [comment]
Hey @JJZHK 

It's an own theme called materialshell is open-source and you can get it on github here.

[materialshell](https://github.com/carloscuesta/materialshell).

For this kind of questions, please ping me on twitter [@crloscuesta](https://twitter.com/crloscuesta)
