### ISSUE TITLE
[FEATURE] ✨ Conventional Commits support! 🎉

### ISSUE THREAD

**Issue by DoubleU23** [carloscuesta/gitmoji-cli#145]
Hello @carloscuesta!

I've added support for CC,  
hope you are willing to add it to your awesome tool.

here is the PR #144 

detailes can be discussed - please give feedback

## :sparkles: added feature conventionalCommits

using [@stack23/gitmoji-conventional-commits^3.2.9](https://github.com/stackr23/gitmoji-conventional-commits#v3)  
the emoji gets replaced with [Conventional Commit Prefixes](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#examples)  
__f.e.__ `🐛` =>  `fix(🐛): `

> can be enabled via `config.getConventionalCommits()`

## Tests - help needed
> 🎊 im already using it - see last few commits in PR!
  * [ ] add tests to hit expected coverage

### TBD (next) - advanced format

* use scope if available - `fix(<scope>): 🐛`
  * __decision to make:__  ❓ 
    - use `emoji.scope` - according to emoji description  
    - use extra input option in `prompts.gitmoji`
  * maybe use code of #139

**Comment by DoubleU23** [comment]
need help with jest snapshots, did never work with them.

**Comment by rishichawda** [comment]
@DoubleU23 Just a thought, isn't the emoji already supposed to convey the kind of commit? For example, 🐛 is already supposed to specify that it's a bug fix, so having both of them would just eat up the commit message length. Don't you think?

**Comment by DoubleU23** [comment]
I understand if you dont want it to be in your package,  
But maybe you should consider to get more infromend about conventional commits,  
Which is also connected to semantic versioning and tools like semantic-release and changelog generators.

So im still using it for myself  
My package is supposed as bridge to other tools like commitizien and others,  
So maybe youre interested in adding some constructive input how to structure an implementation without bothering you with codechanges.

You can see an example at my packages CHANGELOG.md  
where i used an scope pattern ` fix(scope): emoji` which helps to identify the specific task  
And as the cli user doesnt want to input all three task definitions its best to select tne specific (through your relations) and  prefix them with CC related keywords.

**Comment by carloscuesta** [comment]
Hey @DoubleU23 

Thanks for your suggestion, IMHO I prefer to stick to the original idea of using an emoji to replace those kind of things, that's what the convention it's all about!

Thanks! <3

**Comment by vivaxy** [comment]
https://github.com/vivaxy/gacp might be your choice.

**Comment by DoubleU23** [comment]
thx for the suggestion!
since `commitlint` and `conventional-commits` are now located at the "same maintainers"  
and is now handled with an more modular approach, we now use our own `commitlint-config` and plan to also implement an own parser for it as the "new" module approach also supports that

but for private usage i'll try it out, and may use it for some smaller projects :)
