### ISSUE TITLE
[Feature Request] Add word tags/fuzzy search to improve searching

### ISSUE THREAD

**Issue by m-roberts** [carloscuesta/gitmoji-cli#147]
Hello @carloscuesta!

I was wondering if it would be possible to consider adding synonyms to words included in the full text descriptions to improve results. Allowing for a partial match would be very helpful too. Being able to to search for synonyms of the emoji string would also be helpful.

For example:

| Search For | Result Shown             |
|------------|--------------------------|
| comment    | Documenting source code. |
| Jenkins    | Adding CI build system.   |
| add asset    | Adding or updating assets.   |
| move    | Moving or renaming files.   |
| emergency    | Critical hotfix.   |
| poo    |  Writing bad code that needs to be improved.   |

In particular, because it is [recommended to use imperative mood in the subject line of a Git commit](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53#rules-for-a-great-git-commit-message-style) (i.e. A properly formed Git commit subject line should always be able to complete the following sentence: `If applied, this commit will <your subject line here>`), allowing for searching of words such as `move` instead of `moving` is helpful.

This would make finding the most appropriate emoji a lot easier.

**Comment by carloscuesta** [comment]
Hey @m-roberts 

I agree with it, we can improve a lot the search of emojis with the cli!
