### ISSUE TITLE
[Improvement] Increase remote fetch timeout

### ISSUE THREAD

**Issue by cleitonper** [carloscuesta/gitmoji-cli#152]
Hello @carloscuesta!

After `gitmoji-cli` installation, when I run the `gitmoji -l` command the following error is returned:

```bash
ERROR: Network connection not found - ECONNABORTED
ERROR: gitmoji list not found - undefined
```

I changed the `gitmoji.js` file at *line 205* to view more details about the **Network connection not found** error, and I discovered that this problem is related to axios timeout configuration;

```diff
# gitmoji.js

.catch((error) =>
-  this._errorMessage(`Network connection not found - ${error.code}`)
+  this._errorMessage(`Network connection not found - ${error.message}`)
)
```

With this change, the error was changed

```bash
# from this
ERROR: Network connection not found - ECONNABORTED
# to this
ERROR: Network connection not found - timeout of 5000ms exceeded
```

Increasing `axios timeout` in util.js file *from 5000 to 30000* solves this problem.

```diff
# utils.js

const gitmojiApiClient = axios.create({
  baseURL: 'https://raw.githubusercontent.com/carloscuesta/gitmoji/master',
-  timeout: 5000,
+  timeout: 30000,
  headers: {},
  params: {}
})
```

**Ps:** A feedback message in `_fetchRemoteEmojis()` method should be placed, to avoid a unexpected `CTRL + C` during the fetch.

___

Maybe this issue is related to #40 and #49.

**Steps to reproduce**: 
- `npm i -g gitmoji-cli`
- `gitmoji -l`

**OS**: KDE neon 5.14
**gitmoji -v**: 1.9.2
**Node version**: 10.15.0

**Error Message**: 

| ![gitmoji-error-1](https://user-images.githubusercontent.com/13934790/51428329-9b661800-1be9-11e9-94bc-2c7c23e73703.png) |
|:--:| 
| *Error with code(ECONNABORTED)* |

| ![gitmoji-error-2](https://user-images.githubusercontent.com/13934790/51428363-fc8deb80-1be9-11e9-8306-35e636fd2520.png) |
|:--:| 
| *Error with messge(timeout of 5000ms exceeded)* |

**Proposed fetch feedback message**:

| ![gitmoji-fetching](https://user-images.githubusercontent.com/13934790/51428434-bedd9280-1bea-11e9-87c5-e4c4633c8458.png) |
|:--:| 
| *Hey there! We're fetching the emoji list for you.* |

**Comment by carloscuesta** [comment]
That's perfect and makes sense, feel free to send a PR! ✨
