### ISSUE TITLE
How does the auto git add . feature actually work?

### ISSUE THREAD

**Issue by paulywill** [carloscuesta/gitmoji-cli#168]
Hello @carloscuesta 😎!

How does the auto git add . feature actually work?

And can you add some more documentation about it?

**Comment by carloscuesta** [comment]
Hello @paulywill

The auto git add configuration. Basically runs `git add .` for you when running gitmoji.

That means that you don’t need to add the files yourself

https://git-scm.com/docs/git-add

**Comment by paulywill** [comment]
@carloscuesta Does this feature work when activating or using the hook?

**Comment by carloscuesta** [comment]
Not really, because we assume that when you use a commit hook, you handle the process of adding the files manually since you don’t want to run the gitmoji command at all. You’re using it within the `git commit` message
