### ISSUE TITLE
Enter "#." Always prompt error?

### ISSUE THREAD

**Issue by xieyezi** [carloscuesta/gitmoji-cli#171]
Hello @carloscuesta!

 because my github project have no isses,so when I choose "Issue / PR reference:" ,I enter "#." ,but there are some tips always  popping up.
Issue: 

➜  Music git:(master) ✗ gitmoji -c
#$ Choose a gitmoji: 📝  - Writing docs.
#$ Enter the commit title [13/48]: update readme
#$ Enter the commit message: update readme.md
#$ Issue / PR reference: #.
Always show this tips👇:
>> Enter the number of the reference without the #. Eg: 12

mac OS10.14.4
**gitmoji-cli -v**:
1.9.2
**Node version**:
v9.3.0

how to solve this problem？？

**Error Message**: 
>> Enter the number of the reference without the #. Eg: 12

![QQ20190418-030814@2x.png](https://i.loli.net/2019/04/18/5cb779b7253ad.png)

**Comment by Bhupesh-V** [comment]
I am having the same issue
It's not always necessary that someone would have a issue/PR to refer

**Comment by carloscuesta** [comment]
Hey @xieyezi if you don't have any reference just leave this field empty, the prompt will continue.

I'm refactoring this in #102

**Comment by xieyezi** [comment]
@carloscuesta   thanks！
