### ISSUE TITLE
Feature request: Is there a way to reduce the number of choices?

### ISSUE THREAD

**Issue by dialex** [carloscuesta/gitmoji-cli#177]
Hello @carloscuesta!

Feature request:

I know I can filter/search for a commit type... but what would really speed up my flow was if I could reduce the number of options when I do `gitmoji -c`. Like a global config, where I could say the emojis/types that interest me.

Something like e.g. 📦 NEW, 👌 IMPROVE, 🐛 FIX, 📖 DOC, 🚀 RELEASE, and ✅ TEST from [EmojiLog](https://opensource.com/article/19/2/emoji-log-git-commit-messages).

**Comment by dialex** [comment]
Maybe this is what I'm looking for? https://github.com/ngryman/cz-emoji

**Comment by dialex** [comment]
Nevermind, I saw that as I type it filters, so that's good enough. :)

**Comment by carloscuesta** [comment]
Yes, you can search for the emojis while you're commiting just by typing
