### ISSUE TITLE
gpg failed to sign the data

### ISSUE THREAD

**Issue by dialex** [carloscuesta/gitmoji-cli#178]
Hello @carloscuesta!

Issue: 

I tried to make my first commit with gitmoji and I got an error. The commit was not done. If I do a simple `git commit -m "stuff"` it works. So it's not a git config issue.

```
gitmoji -c
? Choose a gitmoji: 📝  - Writing docs.
? Enter the commit title [5/48]: stuff
? Enter the commit message: stuff
? Issue / PR reference: 123
```

**OS**:
**gitmoji -v**: 1.9.2
**Node version**: 10.15.3

**Error Message**: 

```
ERROR: error: gpg failed to sign the data
fatal: failed to write commit object
```

**Comment by dialex** [comment]
Maybe related with #48

**Comment by hartwork** [comment]
And maybe #176 as well

**Comment by dialex** [comment]
Ok this https://github.com/carloscuesta/gitmoji-cli/issues/48#issuecomment-382331970 was the solution. Run `gitmoji -g` and disable signing.
