### ISSUE TITLE
Create a commitizen version for gitmoji

### ISSUE THREAD

**Issue by carloscuesta** [carloscuesta/gitmoji-cli#18]

**Comment by thibmaek** [comment]
I might try to get this one PR'd tomorrow if I find the time ;)

**Comment by Landish** [comment]
Would about this https://github.com/Landish/cz-gitmoji ? Would you mind?

**Comment by carloscuesta** [comment]
Cool! @Landish I'm goint to add as a reference on the docs 🎉
