### ISSUE TITLE
gitmoji -c failed

### ISSUE THREAD

**Issue by Jeff-Tian** [carloscuesta/gitmoji-cli#182]
Hello @carloscuesta!

Issue: 

`gitmoji -c` failed by `failed to write commit object`.

```shell
➜ gitmoji -c
? Choose a gitmoji: 🔧  - Changing configuration files.
? Enter the commit title [15/48]: add prod config
? Enter the commit message: add prod config
? Issue / PR reference:

ERROR: error: gpg failed to sign the data
fatal: failed to write commit object
```

**OS**: macOS
**gitmoji-cli -v**: 1.9.2
**Node version**: v8.11.3

**Error Message**: 

![image](https://user-images.githubusercontent.com/3367820/59659115-0edf7600-91d8-11e9-9c27-08c54a48c9eb.png)

**Comment by QoVoQ** [comment]
Same problem meet.

OS: 4.18.0-16-generic #17~18.04.1-Ubuntu
gitmoji-cli -v: 1.9.2
Node version: v10.15.3

**Comment by carloscuesta** [comment]
Hey @Jeff-Tian this is not an error related with the cli, this is something related with how you set up git comming signing.

If you have not properly disabled signing please take a look at 

https://github.com/carloscuesta/gitmoji-cli/issues/48#issuecomment-382331970
