### ISSUE TITLE
Commiting takes insanely long

### ISSUE THREAD

**Issue by thibmaek** [carloscuesta/gitmoji-cli#19]
Hello @carloscuesta!

Issue: Since updating to 1.2.1 committing with the hook takes insanely long. After 3 minutes or so I quit the command with `Ctrl + c` and as you can see on the screenshot below, commit seems to have gone trough but produces an error about locking HEAD. I do have other git hooks configured (pre-commit and pre-push) but using gitmoji <=1.2.x worked just fine. Omitting the `--no-verify` flag is not relevant to the issue ;)

**OS**: macOS (Latest RC)
**gitmoji-cli -v**: 1.2.1
**Node version**: v7.1.0

**Error Message**: 

![image](https://cloud.githubusercontent.com/assets/6213695/20685161/90c4214c-b5b3-11e6-9a87-6fefa1dfc842.png)

**Comment by carloscuesta** [comment]
Having the same problem too via hook option also when using 1.2.0 that's weird 🤔

**Comment by carloscuesta** [comment]
Apparently found the issue [at this commit](https://github.com/carloscuesta/gitmoji-cli/commit/8b97e4b10a6eed287521a389e801a226e41f9efb).
