### ISSUE TITLE
can't use  "gitmoji -u" to update

### ISSUE THREAD

**Issue by Lichmaker** [carloscuesta/gitmoji-cli#194]
Hello @carloscuesta!

i can't use ` gitmoji -u ` to update gitmoji

Issue: 

when i use ` gitmoji -u ` , it said : ERROR: Network connection not found - ECONNABORTED

mac os 10.14.5 
npm 6.10.1
node v12.1.0

![image](https://user-images.githubusercontent.com/8957712/61687374-ddb51100-ad54-11e9-8125-9d855563a962.png)

**Comment by Lichmaker** [comment]
gitmoji version is 1.9.2

![image](https://user-images.githubusercontent.com/8957712/61687485-1523bd80-ad55-11e9-9e32-9b55e655d32c.png)

**Comment by Lichmaker** [comment]
i think that was a net work problem. 

but something wrong again. :(

![image](https://user-images.githubusercontent.com/8957712/61691213-a139e300-ad5d-11e9-970b-e1bd8ba35d04.png)

i can't update to 1.9.3

![image](https://user-images.githubusercontent.com/8957712/61691232-adbe3b80-ad5d-11e9-938d-16b9b97676ee.png)

**Comment by carloscuesta** [comment]
Hey @Lichmaker as pointed out in the error message, this is a problem related with your connectivity.

**Comment by Lichmaker** [comment]
thank u.  :)
