### ISSUE TITLE
What is "Enter the scope of current changes" ?

### ISSUE THREAD

**Issue by israelKusayev** [carloscuesta/gitmoji-cli#218]

**Comment by sleepyfran** [comment]
Came to ask just this. For what I see if you input anything there it'll append it to the tittle like this:
`🔥 (Scope you entered): Title`

So I guess it's the section of your code for which the changes apply? I don't know.

**Comment by nathan818fr** [comment]
Adding an option to disable it (via the existing `gitmoji --config`) would be nice.
I dont need scopes (and if I really need to specify a scope on few commits I prefer to enter it manually in the title).

**Comment by carloscuesta** [comment]
It's something that we introduced #139 this idea comes from conventional commits to specify the context of your commit, I think will be good to disable this by default and add it as an option

**Comment by carloscuesta** [comment]
Fixed on the new release!
