### ISSUE TITLE
CLI hangs until ctrl+c

### ISSUE THREAD

**Issue by hipstersmoothie** [carloscuesta/gitmoji-cli#22]
Hello @carloscuesta!

Issue: 
When i rund `gitmoji -c` i can go though the prompts until the end, but once i am down it hangs until ctrl+c. It then finishes up the commit. I would expect it to commit without a need for a ctrl+c.

**OS**:
**gitmoji-cli -v**: 1.3.0
**Node version**: 7.0.0 and 7.2.1

**Comment by carloscuesta** [comment]
Is it working for me, what OS are you using? Did you used the --init option before --commit?

**Comment by hipstersmoothie** [comment]
That was definitely the issue! Might wanna put that in the readme somewhere. 👍

**Comment by carloscuesta** [comment]
It's "kind of" explained that you have two options for using the commit option, via hook or gitmoji-cli 🤔
