### ISSUE TITLE
Stuck in terminal, command timeout.

### ISSUE THREAD

**Issue by tolerious** [carloscuesta/gitmoji-cli#224]
Hello @carloscuesta!

Issue: 
`gitmoji -l` command got stuck,  and the emoji can not show.

**OS**: windows 7
**gitmoji-cli -v**:2.2.0
**Node version**:v12.13.0

**Error Message**: 

![image](https://user-images.githubusercontent.com/2922120/68274232-89376680-00a3-11ea-9a4a-2f00697f7243.png)

and then I create a  `gitmojis.json` file. but it didn't work at all.
![image](https://user-images.githubusercontent.com/2922120/68274786-fc8da800-00a4-11ea-8db8-5c5b2dc8952c.png)

**Comment by carloscuesta** [comment]
The command you're pointing to is `gitmoji -c` right? 

Since you don't have any emoji I'm assuming that the fetch failed. Please try to run `gitmoji -u` and see the result of the command, it must likely be a problem with network

**Comment by tolerious** [comment]
> The command you're pointing to is `gitmoji -c` right?
> 
> Since you don't have any emoji I'm assuming that the fetch failed. Please try to run `gitmoji -u` and see the result of the command, it must likely be a problem with network

Yes， I am pointing to the command `gitmoji -c`, now I tried this command `gitmoji -u`, and got this output.

![image](https://user-images.githubusercontent.com/2922120/68292932-daf1e800-00c7-11ea-9046-844ad2399c27.png)

**Comment by tolerious** [comment]
How can I check the network is ok?

**Comment by tolerious** [comment]
And run this command `ping raw.githubusercontent.com` got  `request timeout`.

**Comment by tolerious** [comment]
#49 #152     I refered to these  issues.

**Comment by carloscuesta** [comment]
Seems like you're having problems because your network can't contact to the `raw.githubusercontent.com` host

Are you using some kind of proxy or something like that ?

**Comment by tolerious** [comment]
> Seems like you're having problems because your network can't contact to the `raw.githubusercontent.com` host
> 
> Are you using some kind of proxy or something like that ?

I am in China, so I am blocked to this website, but I used a VPN, and also can not reach the `raw.githubusercontent.com` at all.

**Comment by carloscuesta** [comment]
That's not cool! 😞

Yup, seems like whole GitHub is blocked on China 🇨🇳. Problem is still with your VPN, since you can't reach GitHub.

Sorry I can't help but I don't think I could do much more here

Thanks! 🙏

**Comment by VisonM** [comment]
I opened vpn and run gitmoji -l in the terminal. but terminal output network timed out. Then I closed vpn and run again it worked, it was amazing

**Comment by ThoughtZer** [comment]
just windows？how is it now？

**Comment by quanzhiyuan** [comment]
you can set the hosts file:    151.101.76.133 raw.githubusercontent.com
