### ISSUE TITLE
Test faild on Windows.

### ISSUE THREAD

**Issue by SPGoding** [carloscuesta/gitmoji-cli#226]
Hello @carloscuesta!

The test `test/utils/emojisCache.spec.js` will fail if it is ran on Windows because of the directory sep symbol.

**Issue:**
0. Run `npm t` on Windows.

**OS**: Windows 10
**gitmoji-cli -v**: 3.0.0
**Node version**: 10.16.0

**Error Message**:
![image](https://user-images.githubusercontent.com/15277496/68546753-ecfbbf80-0414-11ea-883c-3f1ef7318725.png)

**Comment by carloscuesta** [comment]
Thanks for reporting this @SPGoding 

Windows.. 😵
