### ISSUE TITLE
Suggestion: Why not convert to Typescript?

### ISSUE THREAD

**Issue by nitaking** [carloscuesta/gitmoji-cli#233]
Hello @carloscuesta!

I will contribute to this library in the future. 
(I built a similar library with TS.: https://github.com/nitaking/gitmoji-c)
But this library is written in js. I thought it was subtle.　

Are you considering building with ts (ts-node)?

**Comment by carloscuesta** [comment]
@nitaking 

At the moment I’m not interested in moving the project to TypeScript. I think that Flow is enough to add type checks.

Btw I saw the clone that you’ve posted. If you’re not interested in using GOG you just need to disable this option through the `gitmoji -g` command. There’s no need to maintain an own fork for that see

https://github.com/carloscuesta/gitmoji-cli#config

**Comment by nitaking** [comment]
I see, thanks for your reply!

> Btw I saw the clone that you’ve posted. If you’re not interested in using GPG you just need to disable this option through the gitmoji -g command. There’s no need to maintain an own fork for that see

This was created before the gpg settings could be changed in config.

I will decide whether to keep it according to my future needs and the policy of this repository.

**Comment by carloscuesta** [comment]
Cool! Feel free to keep the fork 😊
