### ISSUE TITLE
Disable signing

### ISSUE THREAD

**Issue by Mte90** [carloscuesta/gitmoji-cli#24]
I don't want to sign all my commit but everytime i have to remember that I have to put the n for that value
, it's possible to configure what question ask?
Also by commandline will be not very bad

**Comment by carloscuesta** [comment]
Hey @Mte90 thanks for submitting an issue,

The easiest way I see is to add a flag to avoid the Signed commit question, but this is the same as answering "No" at the prompting section.

Probably implementing something like [Yeoman remembering user preferences](http://yeoman.io/authoring/user-interactions.html) for the signed commit will be good.

The other way I see is just to create like a .gitmoji-config file in the `~` directory to remember some user preferences when working with gitmoji 🤔

**Comment by Mte90** [comment]
I think something like that `gitmoji -prompt=title,pr` in that way the field enable are the commit tile and the pr/issue field.
And for remember i will do an aliai in my .bashrc
