### ISSUE TITLE
Error when executing gitmoji --init

### ISSUE THREAD

**Issue by HarborZeng** [carloscuesta/gitmoji-cli#240]
Hello @carloscuesta!

When executing `gitmoji --init`

an error message was showed:

```
✖ Error: Error: Command failed with exit code 128: git rev-parse --absolute-git-dir
```

Issue:

It's my first time to install and use this npm package

**OS**:

PRETTY_NAME="Deepin 15"
NAME="Deepin"
VERSION_ID="15.11"
VERSION="15.11"
ID=deepin
HOME_URL="https://www.deepin.org/"
BUG_REPORT_URL="http://feedback.deepin.org/feedback/"

**gitmoji-cli -v**: 3.0.0
**Node version**: v12.13.0
**git version**: 2.11.0

**Comment by carloscuesta** [comment]
Hey @HarborZeng 

Are you executing the init commit inside a git repository?

**Comment by HarborZeng** [comment]
> Hey @HarborZeng
> 
> Are you executing the init commit inside a git repository?
> 
> Could you try to execute the following command and paste the output?
> 
> ```
> git rev-parse --absolute-git-dir
> ```

No, I executed `gitmoji --init` in my user home dir: `~`.

I executed `git rev-parse --absolute-git-dir`, and the raw output is below:

```
fatal: 不是一个 git 仓库（或者向上递归至挂载点 /home 的任何祖先目录）
停止在文件系统边界（未设置 GIT_DISCOVERY_ACROSS_FILESYSTEM）。
```

That's Chinese, I translated it below FYI:

```
fatal: not a git repository（or recursive to the mount of /home 's any parent directory）
stopped at the system boundary(GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

And then I realized that I should execute `gitmoji -i` in a repo, so I did that, but still the hook not worked.

```
user@host:~/some-path/repo$ gitmoji -i
✖
user@host:~/some-path/repo$ vim index.js
user@host:~/some-path/repo$ git add .
warning: file index.js CRLF will be replaced by LF
file in the workplace will still keep the original line separator.
user@host:~/some-path/repo$ git commit
(then I enter the nano editor)
[master c70c76b] asdatst ttt
 1 file changed, 1 insertion(+), 1 deletion(-)
user@host:~/some-path/repo$ git push
user@host:~/some-path/repo$
```

Well, you can see the commit procedure is not hooked.

**Comment by astromonkee** [comment]
Hi @HarborZeng, @carloscuesta 
I got the same issue. Manually creating the `.git/hooks` folder first before running `gitmoji -i` resolved it for me.

**Comment by HarborZeng** [comment]
> Hi @HarborZeng, @carloscuesta
> I got the same issue. Manually creating the `.git/hooks` folder first before running `gitmoji -i` resolved it for me.

Hi, thanks for sharing the solution with us, but did you create the folder in you `home` dir? Because I did what you suggested in my `~` directory , and it didn't work still.

**Comment by astromonkee** [comment]
@HarborZeng,
No, I created it in the `.git` folder on my repository's root folder.

**Comment by carloscuesta** [comment]
@HarborZeng The `gitmoji --init` command should be executed on a git repository not the `~` directory, that's the problem!
