### ISSUE TITLE
git commit hook on v3 requires to use -m

### ISSUE THREAD

**Issue by ulisesantana** [carloscuesta/gitmoji-cli#255]
Hello @carloscuesta 😎!

I just installed the new version for the CLI and if I try `git commit` the gitmoji CLI will starts and once I fill up the form an error is showed in the terminal. 

However, if you just give some message to the commit `git commit -m "foo"` then the CLI works and the final message is the one you put on the CLI form.

**OS**: macOS Catalina 10.15.2
**gitmoji-cli -v**: 3.0.0
**Node version**: 12.13.0

**Error Message**:
```
hint: Waiting for your editor to close the file... error: cannot run code: No such file or directory
error: unable to start editor 'code'
Please supply the message using either -m or -F option.
```

**Comment by carloscuesta** [comment]
Hey @ulisesantana 

I can't reproduce your error,

<img width="1440" alt="Screenshot 2019-12-21 at 18 36 03" src="https://user-images.githubusercontent.com/7629661/71311633-cae85a80-2420-11ea-878d-af0897778518.png">

Could be this a problem with your enviornment configuration ?

> error: unable to start editor 'code'

Seems that your git is trying to launch the `code` editor to edit the commit message
