### ISSUE TITLE
ctrl-c skip gitmoji prompts stopped working in 3.0.1

### ISSUE THREAD

**Issue by eli-symbolab** [carloscuesta/gitmoji-cli#266]
Hello @carloscuesta!

hi! Thank you for this cool and useful program. I installed the latest 3.0.1 and noticed that the previous behavior of pressing ctrl-c to skip the gitmoji prompt has stopped working. Rolling back to 3.0.0 restored the behavior.

Issue:

Perform a git merge as usual
Run `git commit`, when a gitmoji-cli hook has been installed
The gitmoji prompt appears.
Press ctrl-c
_Expected_: skipping gitmoji, I see the standard Merge message pre-filled in my git commit message editor. Saving and exiting completes the merge.
_Actual behavior_: gitmoji-cli quits, and the commit is canceled.

**OS**: macOS Mojave 10.14.6
**gitmoji-cli -v**: 3.0.1
**Node version**: 6.13.4

**Comment by carloscuesta** [comment]
That should have been caused for one of the dependencies we bumped on `3.0.1`

**Comment by eli-symbolab** [comment]
This behavior is reproducible in 3.1.0 as well.

**Comment by tadejs** [comment]
I confirm on 3.1.0 on Ubuntu 18.04 as well. I was relying on this behavior to make `git commit --amend` work without needing to retype the commit message. Is there any "official" way to skip the dialogue on commit?

**Comment by eli-symbolab** [comment]
Same behavior in 3.2.0.

**Comment by Tydax** [comment]
At first I thought it was a new feature rather than a bug that I was about to ask about because I find it annoying for amending commits and rebasing 😅 . Thank you for reporting this.

Same behaviour in 3.2.1.

**Comment by carloscuesta** [comment]
As I pointed out this should be the reason for the problem: https://github.com/carloscuesta/gitmoji-cli/issues/266#issuecomment-568406983 if anyone is willing to take a look I would really appreciate it! 🙏

**Comment by eli-symbolab** [comment]
Thank you all!!!!!
