### ISSUE TITLE
 failed, reason: connect ECONNREFUSED 151.101.228.133:443

### ISSUE THREAD

**Issue by SnowFlowers** [carloscuesta/gitmoji-cli#271]
Hello @carloscuesta!

Issue:

request to https://raw.githubusercontent.com/carloscuesta/gitmoji/master/src/data/gitmojis.json failed.
**OS**: macos
**gitmoji-cli -v**: gitmoji -c
**Node version**: 8.9

**Error Message**:
connect ECONNREFUSED 151.101.228.133:443

![image](https://user-images.githubusercontent.com/16875486/71497980-7bc57e00-2895-11ea-9735-185a0e61d0fb.png)

**Comment by carloscuesta** [comment]
Hey I think the error clearly points what's the problem, are you from China ?

If the answer is yes this is the problem: https://github.com/carloscuesta/gitmoji-cli/issues/224#issuecomment-550491035
