### ISSUE TITLE
Precommit hook detection conflicts with husky

### ISSUE THREAD

**Issue by KsRyY** [carloscuesta/gitmoji-cli#273]
Hello @carloscuesta!

Issue:

I've setup `husky` and `lint-staged` to check my code before commit, but when I tried to use `gitmoji -c` in that project, it said that I need to remove the hooks in order to use `gitmoji -c`. Is there any way to intergrate this with `husky`?

**OS**: WSL Ubuntu 19.10 (manually updated from 18.04)
**gitmoji-cli -v**: 3.0.1
**Node version**: 12.13.1

**Comment by KsRyY** [comment]
@carloscuesta

**Comment by carloscuesta** [comment]
Fixed in #254
