### ISSUE TITLE
Precise the aim of gitmoji-cli

### ISSUE THREAD

**Issue by welcoMattic** [carloscuesta/gitmoji-cli#3]
IMHO gitmoji-cli got for aim to make gitmojis data available for programatic purpose (like a git hook).

In this case, the option `--init` is not a the right place, I think it should be in gitmoji-commit-hook.

What do you think @carloscuesta?

**Comment by carloscuesta** [comment]
By default If you run `gitmoji` it will run the questions and auto create the commit with the options.

- Selected gitmoji.
- Reference #
- Signed commit
- Commit title.
- Commit message.

The option `--init` it's for automatically creating the git hook template that you need to create manually when using a git hook. This option enables you to commit with `git commit` without using the `gitmoji` command.

Some other options that are available: 

- `--search`: Search for gitmojis.
- `--list`: List all the gitmojis.

**Comment by welcoMattic** [comment]
Oh alright, you want further than me and my gitmoji-commit-hook package ^^' I'll keep mine because I like KISS principle, but you did really good job! 👍

**Comment by carloscuesta** [comment]
Yes of course you can keep yours no problem 😄 it's always great to have different approaches. Thanks for your time @welcoMattic
