### ISSUE TITLE
Consider adding a search functionality when commiting using gitmoji -c

### ISSUE THREAD

**Issue by wextia** [carloscuesta/gitmoji-cli#30]
Hello @carloscuesta!

I find that it would be very convenient to add a emoji search functionality when commiting changes using `gitmoji -c`.

I am referring to this screen:

![](http://oi68.tinypic.com/122gtur.jpg)  

It would be very cool if you could start typing an emoji or the description of one and `gitmoji` automatically started filtering them.

**Comment by carloscuesta** [comment]
Hey @wextia 

Currently there's a search functionality with the search option[`gitmoji -s `](https://github.com/carloscuesta/gitmoji-cli#search).

Thanks for the suggestion, but I'm not planning to do this at the moment 😄

**Comment by wextia** [comment]
Thanks for the reply, @carloscuesta ! Love the tool, btw :smile: .

**Comment by geniusgordon** [comment]
@carloscuesta maybe you can try this package!
https://github.com/mokkabonna/inquirer-autocomplete-prompt

**Comment by carloscuesta** [comment]
I know that package @geniusgordon, feel free to send a PR
