### ISSUE TITLE
Fuzzy search should sort more intelligently / by relevance

### ISSUE THREAD

**Issue by erikhuizinga** [carloscuesta/gitmoji-cli#302]
Hello @carloscuesta!

Fuzzy search, introduced by 🔖 v3.2.0 🎉 (thanks, awesome feature!), shows search results in a seemingly strange order.

Issue:

 1. `gitmoji -c`
 1. Start typing 'test' (to find ✅) character by character:
    1. ![image](https://user-images.githubusercontent.com/19374736/73607227-d7310d00-45b3-11ea-80f4-2f93db7edc88.png)
    1. ![image](https://user-images.githubusercontent.com/19374736/73607239-e912b000-45b3-11ea-9e78-8fad68d7b151.png)
    1. ![image](https://user-images.githubusercontent.com/19374736/73607246-f760cc00-45b3-11ea-8a5c-fed1f21b13d7.png)
    1. ![image](https://user-images.githubusercontent.com/19374736/73607252-05aee800-45b4-11ea-95bc-fc1ac72de576.png)

Notice that ✅ is not found in the last search result, while the word 'test' is almost a direct match with a word in 'updating tests'. As a user I expect the search results to be sorted by relevance, with larger partial word matches having greater relevance.

**OS**: macOS 10.14.6
**gitmoji-cli -v**: 3.2.0
**Node version**: `node -v`: `v13.7.0`

**Error Message**: none

See aforementioned issues steps.

**Comment by adriencaccia** [comment]
Hey @erikhuizinga, thanks for the issue !
I submitted #303 to try and improve the search.
