### ISSUE TITLE
Add --graph=GRAPH_TYPE option

### ISSUE THREAD

**Issue by ewen-lbh** [carloscuesta/gitmoji-cli#305]
Hello @carloscuesta :sunglasses:!
I made a [little python script](https://github.com/ewen-lbh/gitmoji-commits-graphs) that generates a bar chart from a repo, using commit titles to see the distribution of commit types, using the emoji.
I wrote it today, and the code is a bit messy, but I feel like implementing something like this in gitmoji-cli would be interesting!
I would use a new flag `--graph` or `--stats` that takes in the graph type (useful in case we want to extend this with new graphs)

The complete usage would be 
```bash
$ gitmoji --graph commit-types
```

**Comment by yogeshvar** [comment]
💡
We could get all the `emoji.code` from `getEmojis` and run a bash command
`git log --oneline | grep -c ${emoji.code}` to get the count. We can display the stats. 

I'm not sure whether it's the ideal way.

@carloscuesta @ewen-lbh  what do you think about this?

**Comment by carloscuesta** [comment]
Hey @ewen-lbh thanks for your suggestion!

Currently I prefer not adding new features like this to the cli!

Thanks!
