### ISSUE TITLE
Git commits should include an empty line between title and description

### ISSUE THREAD

**Issue by posva** [carloscuesta/gitmoji-cli#31]
Hello @carloscuesta!

Git commits should have an empty line between the title and the description but currently, there's none:

```
📝 Add Readme
This readme bla bla #1
```

should look like

```
📝 Add Readme

This readme bla bla #1
```

**Comment by carloscuesta** [comment]
What's the point about having an empty line between the commit title and the description? @posva 

I'm not sure but, I think that we don't need a break line. With two or more `-m` option lines are concatenated as separate paragraphs.

```bash
git commit -m "Commit title" -m "Commit message"
```

**Comment by posva** [comment]
That blank line allows to clearly separate the title of the commit from the
summary. I couldn't find an official reference for this but it's a some
kind of standard. For instance when writing the commit with vim, it'll
automatically break every 80 characters and highlight the background in red
the second line to tell you you shouldn't write anything there. A project
using this is the erlang repo. On Google there're many posts saying that
but I couldn't find something from git. Maybe I read it on a book

**Comment by carloscuesta** [comment]
@posva If I open my last commit with nano, the blank line appears. Probably https://github.com/carloscuesta/gitmoji-cli/issues/31#issuecomment-284141790 just adds it.

<img width="685" alt="screen shot 2017-03-04 at 11 58 04" src="https://cloud.githubusercontent.com/assets/7629661/23578226/3d456c64-00d2-11e7-807d-a0fcca618971.png">

**Comment by posva** [comment]
Then it may be worth adding it when using as a hook or as an answer. That way, it'll be consistent with the `-m` behaviour

**Comment by carloscuesta** [comment]
It's already when using as a hook

https://github.com/carloscuesta/gitmoji-cli/blob/master/src/gitmoji.js#L110

**Comment by posva** [comment]
You're still missing a `\n` 😛 (for the blank line)

**Comment by carloscuesta** [comment]
Same as before, it's not needed to split the commit title and message works with only one of them 🤔

**Comment by posva** [comment]
It's not needed, but it's a standard that improves readability. That's why I'm asking for it 🙂

**Comment by posva** [comment]
Thanks @carloscuesta !
