### ISSUE TITLE
Hook skipped when committing Git's verbose flag enabled

### ISSUE THREAD

**Issue by Addono** [carloscuesta/gitmoji-cli#313]
Hello @carloscuesta!

Gitmoji hook doesn't activate when committing with Git commit verbose flag (`-v` or `--verbose`) enabled.

Issue:
Behavior can be reproduced by running `git commit -v` on a repository with the Gitmoji hook enabled. Now, the default commit message editor will be shown instead of the one from Gitmoji CLI.

**OS**: MacOS
**gitmoji-cli -v**: 3.2.1
**Node version**: 12.16.1

Root cause:
The hook in `.git/hooks/prepare-commit-message` checks for lines not starting with `#` in the commit message. If one is found, then the script assumes the commit message is already set. 

However, Git commit is called with the verbose flag enabled, a cut line is included followed by the diff of this commit. This diff is not commented out and as such the Gitmoji hook is skipped.

This is an example of an empty commit message generated with the verbose flag enabled.
```
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch master
# Your branch is up to date with 'origin/master'.
#
# Changes to be committed:
#       modified:   README.md
#
#
# ------------------------ >8 ------------------------
# Do not modify or remove the line above.
# Everything below it will be ignored.
diff --git a/README.md b/README.md
index 2d2e1d0..ec71c5e 100644
--- a/README.md
+++ b/README.md
@@ -28,10 +28,11 @@
... [remainder of the diff]
```

**Comment by Addono** [comment]
For context, I started running into this issue when my Git aliases default to using the verbose flag - which I appreciate for committing on projects not using Gitmoji.

**Comment by carloscuesta** [comment]
That was introduced in #247. Going to merge your PR now ❤️
