### ISSUE TITLE
Slow down GIF demo

### ISSUE THREAD

**Issue by alexislefebvre** [carloscuesta/gitmoji-cli#325]
Hello @carloscuesta!

The demo as a GIF is nice, but I find it too fast to have time to understand what is happening.

Issue:

Here is current version of the .gif:

> ![GIF](https://cloud.githubusercontent.com/assets/7629661/20454643/11eb9e40-ae47-11e6-90db-a1ad8a87b495.gif)

I think that actions go too fast.

Is it possible to add a little delay between each input?

**OS**:
**gitmoji-cli -v**: -
**Node version**: -

**Error Message**:
-

**Comment by carloscuesta** [comment]
Hey @alexislefebvre 

You can read the docs and screenshots to understand the whole process

Thanks!
