### ISSUE TITLE
Add a new setting to customize commit message pattern

### ISSUE THREAD

**Issue by thomasbrodusch** [carloscuesta/gitmoji-cli#328]
Hello @carloscuesta!

Sometimes, git commit convention used by some companies differ from gitmoji-cli commit template. For exemple, in my company, we need to put issue's ID in commit title placed before the emoji. 

It would be awesome if we added a new gitmoji-cli's settings option to define commit message template:

By default:
```
:emoji: :title: :message:
```
Custom setting
```
:title: :emoji: :message:
```
What do you think about it @carloscuesta :) ?

**Comment by carloscuesta** [comment]
Hey @thomasbrodusch 

Thanks for your suggestion. I would prefer not adding this as a feature since I think we’re allowing too much configurations and I would prefer to make fewer things and better that a lot of them for now

Thanks!
