### ISSUE TITLE
[Feature] Change position of emoji in mode client.

### ISSUE THREAD

**Issue by igorwessel** [carloscuesta/gitmoji-cli#367]
Hello @carloscuesta!

Thank you for this CLI is perfect, I missed felt some setting to leave the emoji at the beginning or end of the message, i managed to create the feature but it only makes the commit command after pressing CTRL + C

![Captura de tela de 2020-05-01 20-34-58](https://user-images.githubusercontent.com/54173994/80861286-005d4a00-8c44-11ea-8307-d6e3d5c66473.png)

I know we can use hook mode for edit commit message and changes position of emoji but i think it's awesome if in client mode have some configuration for emoji position in commit message.

**Comment by carloscuesta** [comment]
Hey @igorwessel the whole convention is built up with appending the emoji as the first character in order to know the purpose of the commit. I don't think we want to give the option to place it at the end!

Thanks!
