### ISSUE TITLE
Error occurred unexpectedly when committing with bookmark emoji

### ISSUE THREAD

**Issue by motss** [carloscuesta/gitmoji-cli#37]
_Moved from [gitmoji#114](https://github.com/carloscuesta/gitmoji/issues/114)_

Hello @carloscuesta!

Issue: 

Unable to commit successfully with :bookmark:.

**OS**: macOS Sierra 10.12.4
**gitmoji-cli -v**: 1.5.0
**Node version**: 7.8.0

**Error Message**: 

`ERROR:`

<img width="361" alt="screen shot 2017-04-06 at 2 21 48 pm" src="https://cloud.githubusercontent.com/assets/10607759/24740582/73b8353a-1ad4-11e7-8a4a-224b623d9265.png">

**Comment by carloscuesta** [comment]
I have no problems commiting withs this, you have your changes staged? @motss 

![screen shot 2017-04-08 at 23 17 23](https://cloud.githubusercontent.com/assets/7629661/24832475/a1c79d74-1cb1-11e7-9cac-aa8409b1e1f5.png)

**Comment by motss** [comment]
@carloscuesta The **ONLY** change in my commit that produces this error:

```patch
// package.json

- "version": "0.4.0",
+ "version": "0.4.1",
```

**Comment by carloscuesta** [comment]
@motss I'm not having problems, please check out that you're changes are staged if you don't have the auto add enabled. I think this issue it's not related with the cli.

![screen shot 2017-04-09 at 09 05 02](https://cloud.githubusercontent.com/assets/7629661/24835474/aa5b8e76-1d03-11e7-87ec-6138694ec615.png)
