### ISSUE TITLE
Idea : Create a release note based on git history

### ISSUE THREAD

**Issue by Clebiez** [carloscuesta/gitmoji-cli#376]
Hello @carloscuesta!
Thank you for this repo 👍 

What about creating a command to take a list of commit and transform it into a release note (Features, bugs, enhancements, stacked together) ?

The command should parse the list of commits from HEAD until a hash or another branch / tag ?

**Comment by leandrokanis** [comment]
There is a package that does it:

https://github.com/frinyvonnick/gitmoji-changelog

**Comment by carloscuesta** [comment]
Yes as @leandrokanis this is already covered by gitmoji-changelog
