### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by Thinking80s** [carloscuesta/gitmoji-cli#377]
Hello @carloscuesta!

Issue:

![image](https://user-images.githubusercontent.com/338079/82135490-e58af800-9835-11ea-86a7-e4f46b2d271f.png)

node : 6.5.0
**OS**:
**gitmoji-cli -v**:
**Node version**:

**Error Message**:
SyntaxError: Unexpected token ...

**Comment by carloscuesta** [comment]
As stated on the release notes, gitmoji-cli v3 dropped support for the Node.js version that you're using

https://github.com/carloscuesta/gitmoji-cli/releases/tag/v3.0.0
