### ISSUE TITLE
timedPromise.finally is not a function

### ISSUE THREAD

**Issue by realsarm** [carloscuesta/gitmoji-cli#395]
Hello @carloscuesta :sunglasses:!

### I can not commit using gitmoji-cli it says
As I initiate hook
`✖ Error: TypeError: Command failed: git rev-parse --absolute-git-dir
timedPromise.finally is not a function`
or this as use -c argument
`? Choose a gitmoji: �  - Improving structure / format of the code.
? Enter the commit title [23/48]: refomat PatientInfo.jsx
? Enter the commit message: reformat using cntrl alt l
{ TypeError: Command failed: git rev-parse --absolute-git-dir
timedPromise.finally is not a function
    at setExitHandler (/usr/local/lib/node_modules/gitmoji-cli/node_modules/execa/lib/kill.js:102:29)
    at execa (/usr/local/lib/node_modules/gitmoji-cli/node_modules/execa/index.js:100:22)
    at isHookCreated (/usr/local/lib/node_modules/gitmoji-cli/lib/utils/isHookCreated.js:20:34)
    at withClient (/usr/local/lib/node_modules/gitmoji-cli/lib/commands/commit/withClient/index.js:26:42)
    at _inquirer.default.prompt.then.answers (/usr/local/lib/node_modules/gitmoji-cli/lib/commands/commit/index.js:29:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  originalMessage: 'timedPromise.finally is not a function',
  shortMessage: 'Command failed: git rev-parse --absolute-git-dir\ntimedPromise.finally is not a function',
  command: 'git rev-parse --absolute-git-dir',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false }
{ TypeError: Command failed: git commit -S -m � refomat PatientInfo.jsx -m reformat using cntrl alt l
timedPromise.finally is not a function
    at setExitHandler (/usr/local/lib/node_modules/gitmoji-cli/node_modules/execa/lib/kill.js:102:29)
    at execa (/usr/local/lib/node_modules/gitmoji-cli/node_modules/execa/index.js:100:22)
    at withClient (/usr/local/lib/node_modules/gitmoji-cli/lib/commands/commit/withClient/index.js:33:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  originalMessage: 'timedPromise.finally is not a function',
  shortMessage: 'Command failed: git commit -S -m � refomat PatientInfo.jsx -m reformat using cntrl alt l\ntimedPromise.
finally is not a function',
  command: 'git commit -S -m � refomat PatientInfo.jsx -m reformat using cntrl alt l',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false }`

**Comment by carloscuesta** [comment]
What version of gitmoji-cli are you using ?

**Comment by realsarm** [comment]
3.2.6

**Comment by carloscuesta** [comment]
What operating system ?

**Comment by carloscuesta** [comment]
I can't reproduce your error, could you provide more information about your environment ?

Fill the following template please:

**OS**:
**gitmoji-cli -v**:
**Node version**:

![Screenshot 2020-06-16 at 15 47 00](https://user-images.githubusercontent.com/7629661/84782780-b8726680-afe8-11ea-8637-4589ed2bb9f2.png)

**Comment by realsarm** [comment]
> What operating system ?
WSL 1 on Windows 10

**Comment by realsarm** [comment]
> I can't reproduce your error, could you provide more information about your environment ?
> 
> Fill the following template please:
> 
> **OS**: Ubuntu 18 on WSL 1
> **gitmoji-cli -v**:3.2.6
> **Node version**:6.144.55
> 
> ![Screenshot 2020-06-16 at 15 47 00](https://user-images.githubusercontent.com/7629661/84782780-b8726680-afe8-11ea-8637-4589ed2bb9f2.png)

![image](https://user-images.githubusercontent.com/37932944/84782863-d1d1dd80-affd-11ea-8ecd-267eb134579e.png)

**Comment by realsarm** [comment]
https://user-images.githubusercontent.com/37932944/84783095-178ea600-affe-11ea-993f-235a9887b44c.png)

**Comment by carloscuesta** [comment]
The minimum required node version for using this package is `10`. You should upgrade your node.js 

https://github.com/carloscuesta/gitmoji-cli/blob/master/package.json#L6
