### ISSUE TITLE
[Feature Request] Integrate spell checking to gitmoji-cli

### ISSUE THREAD

**Issue by realsarm** [carloscuesta/gitmoji-cli#396]
[Aspell](http://aspell.net/) can be used or whatever spell checking packages to correct spelling of both title and description automatically

**Comment by carloscuesta** [comment]
This is a brilliant idea!

**Comment by carloscuesta** [comment]
Hey @realsarm I think this is a good idea, however I do not see a clear way of implement this into a cli terminal. I'm not considering this for now!

Thanks for your idea ❤️

**Comment by realsarm** [comment]
It's possible to colorize typos as typing then pressing tab or cmd-space at the end of typos displays a fish shell like suggestion 

It's possible also for user to ignore the colorized words
