### ISSUE TITLE
[Feature discussion] Rebase and --no-edit behaviour with hook

### ISSUE THREAD

**Issue by Larandar** [carloscuesta/gitmoji-cli#397]
Hello @carloscuesta!

I would like to reopen issue #197 with a larger discussion because, unfortunately, the current behaviour makes it difficult to use git workflows which are semi-linear or linear and require rebasing.

**Use-case:**
 
Usually, my workflow requires to branch from master and then rebase before making my MR with both compacting my history and making sure current master changes does not conflict with my branch. And then before merging rebasing a last time so that history is semi-linear.

**Possible solutions I see:**

1. Detecting --no-edit 
2. An option to disable gitmoji temporary, or during rebases.
3. Pre-filling the CLI with the current commit message if detected, making pressing enter 3 times all that is needed

**My thoughts on each solution**

1. Seem impossible currently, but maybe is-it a use-case to improve mainstream git? Knowing if the --no-edit flag is on from the prepare-commit-msg may be a legitimate question.
2. Nice but does not make the workflow that much better.
3. Seem the easier solution, and is more elegant than CTRL+C but not a lot more.

**Comment by carloscuesta** [comment]
The problem is specifically with the hook right? I use rebase workflow also and have no problems using gitmoji-cli as I would normally do

**Comment by carloscuesta** [comment]
We have a PR for this but is currently blocked due to: https://github.com/carloscuesta/gitmoji-cli/pull/366#issuecomment-626140318

**Comment by carloscuesta** [comment]
Solved by @Jeremie-Chauvel, I'm releasing it now!
