### ISSUE TITLE
Interactive prompt config 

### ISSUE THREAD

**Issue by labg94** [carloscuesta/gitmoji-cli#404]
Hello @carloscuesta 😎!

There should be an option where the prompt dialogue will not be needed, due usually I use Intellij Commit dialog to make the commits, but then it throws an error due the prompt dialogue, if there any possibility when I do a normal commit it gets de message and then do all gitemoji magic.

even I made a ticket for the jetbrains team: https://intellij-support.jetbrains.com/hc/en-us/requests/2730906
and they suggest this "To solve this you can reconfigure the hook so it shows a prompt in GUI (not requiring interactive shell)."  

Issue:
Commiting from intellij

**OS**: macOs Catalina 10.15.5
**gitmoji-cli -v**: 3.2.6
**Node version**: v14.4.0

**Error Message**: .git/hooks/prepare-commit-msg: line 3: /dev/tty: Device not configured

<img width="366" alt="Screen Shot 2020-06-27 at 00 15 56" src="https://user-images.githubusercontent.com/26802959/85914424-69f47180-b80b-11ea-9426-f03f343e4e6e.png">

**Comment by carloscuesta** [comment]
I think you can solve this by specifying the $EDITOR environment variable on your Shell.

I don’t think we strictly need to change the contents of the hook.

Try to set the following variable on your shell and try again.

**Comment by labg94** [comment]
I tried but it did not work 😞, it still shows the same message

**Comment by carloscuesta** [comment]
Then you'll need to set the EDITOR also as a configuration on your global `gitconfig`

See:

https://stackoverflow.com/questions/2596805/how-do-i-make-git-use-the-editor-of-my-choice-for-commits

**Comment by labg94** [comment]
nothing yet,

I still think that what jetbrains team says make sense: 
"The error comes from git hook. It seems you have a prepare-commit-msg hook that prompts something on the command line.

But there is no interactive shell is available when git is run by an app (IDEA in this case, but will probably happen when called from other GUI apps too).
That is why the hook fails.

To solve this you can reconfigure the hook so it shows a prompt in GUI (not requiring interactive shell)."

because I do not use the console, Intellij actually shows  this window (image attached), then it make the commit by itself.
 
<img width="1482" alt="Screen Shot 2020-06-27 at 15 24 55" src="https://user-images.githubusercontent.com/26802959/85930436-67852c80-b88a-11ea-97e7-baa50099e260.png">

**Comment by carloscuesta** [comment]
Feel free to send a PR if you can figure out the issue!

**Comment by carloscuesta** [comment]
Brw this cli is meant to be used from a Terminal, not an IDE just in case the purpose of it it’s not understood
