### ISSUE TITLE
Emojis by context

### ISSUE THREAD

**Issue by babakks** [carloscuesta/gitmoji-cli#414]
Hello @carloscuesta!

I've recently gathered a somehow comprehensive context-based table of emojis, that would help a lot a developer to find the right emoji for his/her intent. Have a look, if you would, and see if you can include it as a new feature for the `gitmoji-cli`. Of course, I'm eager to receive any feedback or suggestion.

You can find my post here:  
https://dev.to/babakks/emojis-for-better-git-commit-messages-52fa

**Comment by carloscuesta** [comment]
Hey @babakks I already discussed this on the gitmoji repo and I don't particularly want to create categories!

Thanks for the suggestion
