### ISSUE TITLE
HELP：usage on CentOS?

### ISSUE THREAD

**Issue by yaohuangguan** [carloscuesta/gitmoji-cli#422]
![image](https://user-images.githubusercontent.com/43796777/87743952-c5b78680-c81c-11ea-8e4c-2e0e13286f7e.png)
this is on CentOS, i dont know why gitmoji -i hook gives me a X and gitmoji -c fetching the list hanging....

**Comment by carloscuesta** [comment]
Hey @yaohuangguan 

Thanks for opening an issue, I don't think this is related with `centOS` the real problem should be https://github.com/carloscuesta/gitmoji-cli/issues/224#issuecomment-550491035
