### ISSUE TITLE
automatic "git add ." doesn't work

### ISSUE THREAD

**Issue by JamesHopbourn** [carloscuesta/gitmoji-cli#427]
Hello @carloscuesta!

Issue: automatic "git add ." doesn't work

**OS**: macOS 10.15.5
**gitmoji -v**: 3.2.6
**Node version**: v13.13.0

**Error Message**:
$ gitmoji -g
? Enable automatic "git add ." Yes
? Select how emojis should be used in commits 😄
? Enable signed commits Yes
? Enable scope prompt No

$ gst
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   home/.zshrc
no changes added to commit (use "git add" and/or "git commit -a")

$ gc
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   home/.zshrc

no changes added to commit (use "git add" and/or "git commit -a")

![截屏2020-07-24 上午9 49 34](https://user-images.githubusercontent.com/18232831/88354295-053d2000-cd93-11ea-8803-3133d29182bb.png)
![截屏2020-07-24 上午9 49 38](https://user-images.githubusercontent.com/18232831/88354293-02422f80-cd93-11ea-88e2-e7eb796bafc8.png)

**Comment by carloscuesta** [comment]
The automatic git add is executed once you launch gitmoji -c 

Have you tried in that way?

**Comment by JamesHopbourn** [comment]
> The automatic git add is executed once you launch gitmoji -c
> 
> Have you tried in that way?

Thanks
