### ISSUE TITLE
Git Hook Opening COMMIT_EDITMSG File

### ISSUE THREAD

**Issue by tay1orjones** [carloscuesta/gitmoji-cli#43]
Hello @carloscuesta!

Great work on this - such a great addition to my workflow. I'm running into an issue with using the git hook.

Issue: 

 I've already set up the git hook per the documentation. When I `git commit`, the CLI prompts me as intended and works great. I finalize my message, hit enter, and the commit is committed.

Next is the issue - at the same time when I hit enter to submit, the `COMMIT_EDITMSG` is opened up in my default editor (vscode). Also happening to colleagues who do not have a default editor setup, and it opens the file there in vim.

Ideally this file wouldn't open. Thoughts?

**macOS 10.12.4**:
**gitmoji 1.5.2**:
**Node v7.8.0**:

![image](https://cloud.githubusercontent.com/assets/3360588/25249782/c55190c6-25d8-11e7-887d-76150e429a4b.png)

**Comment by carloscuesta** [comment]
🤔
