### ISSUE TITLE
Config option - text mode (boring mode 😞)

### ISSUE THREAD

**Issue by squidsoup** [carloscuesta/gitmoji-cli#437]
Hello @carloscuesta!

I love gitmoji-cli, and I really appreciate the care you've taken with the UX. Installing and using the tool is a breeze.

My team seems to be embracing conventional commits, which I'm really pleased with. I'd love to share gitmoji-cli with them, however on the whole the consensus in the team is we'd rather not have emojis in commit messages. There's great value in being able to be prompted for scoping (we use that regularly in monorepos), and have contextual help for finding the right conventional commit type (e.g. "core", "fix"), and gitmoji-cli already has great UX for this (just with emojis). Could you find it in your heart to provide a boring/text mode?

I fully understand how completely boring this request is, and appreciate if gitmoji-cli wants to remain committed to being fun.

**Comment by carloscuesta** [comment]
Hey @squidsoup 

Thanks for opening the issue!

I would say the whole purpose of the cli is using emojis on commit messages, so makes no sense to introduce a "text" mode for the changes. 

I think what you're looking for your team is something like [cz-cli](https://github.com/commitizen/cz-cli) it's a cli similar to gitmoji that allows you to follow the conventional commits standard. This is a better fit for you! ❤️ 

Have a great day 😊

**Comment by squidsoup** [comment]
Thanks @carloscuesta, cz-cli looks perfect.
