### ISSUE TITLE
Add support for JIRA references

### ISSUE THREAD

**Issue by randompixel** [carloscuesta/gitmoji-cli#44]
Hello @carloscuesta!

When using gitmoji-cli, I would like to be able to use JIRA references rather than implicitly using github.com ones. This should be a configurable option with the default behaviour being github.com.

You can use JIRA with github repositories. Also Bitbucket cloud and server (from v5) both have emoji support.

I have a pull request ready to go, but please go easy on me - it's my first Node PR! :)

Issue: 
Enter a commit and when prompted type a JIRA reference. Validation fails as it expects just a number. The code will then prefix that number always with a `#`

**OS**: MacOS + ZSH
**gitmoji-cli -v**: 1.5.2-dev
**Node version**:

**Comment by carloscuesta** [comment]
Sure!

Feel free to open the pull request 👍

**Comment by thedmeyer** [comment]
What happened to this? It seems that `Issue / PR reference #` is no longer part of `gitmoji -c` 

@carloscuesta

**Comment by carloscuesta** [comment]
You can specify it on the message prompt @thedmeyer

**Comment by thedmeyer** [comment]
That makes sense. However, I was hoping it would enforce a Jira ticket number in the commit message

**Comment by carloscuesta** [comment]
Not really, you could add it if you want on the message, there's no reason to enforce JIRA/GH issue references on the prompts. Basically under the hood what that prompt made was to set this reference into the message and I wanted to simplify the prompts and configuration options of the cli.

That's why we removed it!
