### ISSUE TITLE
Commit hook is not working anymore since 3.2.9 upgrade

### ISSUE THREAD

**Issue by vanwalj** [carloscuesta/gitmoji-cli#444]
Hello @carloscuesta!

Issue:
whenever I `git commit` I get this error message: `A commit message is already set, cancelling gitmoji`

I was using Gitmoji through the git commit hook, setup with gitmoji -i and everything was working fine but it stoped working after upgrading to 3.2.9

**OS**: macOS 10.15.6 (19G2021)
**gitmoji -v**: 3.2.9 installed via brew
**Node version**: 14.8.0
**Git version**: 2.28.0

**Error Message**:
A commit message is already set, cancelling gitmoji

Thanks!

**Comment by carloscuesta** [comment]
That's probably related with the change we introduced at https://github.com/carloscuesta/gitmoji-cli/pull/415 @Jeremie-Chauvel could you take a look at it ? :pray:

**Comment by oakreef** [comment]
I am also experiencing this this morning. I have no other hooks set up or anything else that would be setting a commit message and when I go to commit it opens up my editor with a blank commit message. Nevertheless gitmoji is displaying the line `A commit message is already set, cancelling gitmoji`

**OS:** Ubuntu 20.04
**gitmoji:** 3.2.9
**Node:** 10.19.0
**Git:** 2.25.1

gitmoji installed via npm

**Comment by carloscuesta** [comment]
Yes I reproduced the error, I'm going to revert #415 and release a new version until we found a fix for that

**Comment by vanwalj** [comment]
Awesome, thanks for your work btw!

**Comment by carloscuesta** [comment]
Sorry for the inconvenience 😅 

This should been fixed on `3.2.10` which is published right now.

@Jeremie-Chauvel I reverted #415. If you could take a look to fix this regression we could integrate it again on the cli.

**Comment by Jeremie-Chauvel** [comment]
Hi @carloscuesta 
Sorry for the inconvenience, I will look into it.
Might need to drop the current way of detecting no interactive (based on presence of git message) and instead use `git status` or some less clever way of detecting that the hook shouldn't be launched.
