### ISSUE TITLE
Missing emoji like :lightbulb:

### ISSUE THREAD

**Issue by motss** [carloscuesta/gitmoji-cli#45]
Hello @carloscuesta!

Noticed some missing emoji using the `gitmoji-cli` on macOS vs the `gitmoji-cli` on Windows 10.

Issue: 

Missing emoji includes 💡 , 🍻 , and many more.

**OS**:
**gitmoji-cli -v**: 1.5.2
**Node version**: 6.10.2
**OS**: macOS Sierra 10.12.4

**Error Message**:

**Comment by carloscuesta** [comment]
Because the gitmoji-cli creates a cache to work offline, see [gitmoji-cli update](https://github.com/carloscuesta/gitmoji-cli#update).

`gitmoji -u`

**Comment by motss** [comment]
👍
