### ISSUE TITLE
[Feature request] Prefill title and message in hook mode

### ISSUE THREAD

**Issue by adriencaccia** [carloscuesta/gitmoji-cli#452]
Hello @carloscuesta!

When using the hook mode, there is no way to access the previous commits title and message (in my terminal command history for example).
Indeed, I find it very useful to use commands like `git commit -m "Title" -m "Message"`, that way I can quickly access it back in the future using my terminal command history.

In this regard, I propose a feature to prefill title and message in hook mode:

![gitmoji-prefill-hook](https://user-images.githubusercontent.com/19605940/90916131-d42b2c00-e3e0-11ea-8029-c977399b12f7.gif)

Since I really love this feature, I already submitted a PR #446 contaning a possible implementation.

What do you think of this feature ?

**Comment by Jeremie-Chauvel** [comment]
I would be very interested in this feature as well

**Comment by art049** [comment]
Currently this missing feature is the only thing preventing me from using gitmoji.
Having to retype the commit message every time is very annoying.
Please take this in consideration @carloscuesta .

**Comment by carloscuesta** [comment]
Sure I will take a look at the PR

**Comment by carloscuesta** [comment]
PR reviewed, thanks! 😊
