### ISSUE TITLE
[Feature request] add option to edit last commit

### ISSUE THREAD

**Issue by israelKusayev** [carloscuesta/gitmoji-cli#460]
Hello @carloscuesta!

It would be great if gitmoji-cli could provide an option to edit the last  (unpushed) commit

As we can do: `git commit --amend -m "New commit message"`

**Comment by israelKusayev** [comment]
`gitmoji -c --amend`

**Comment by carloscuesta** [comment]
I don't think it's worth to support all those features because we will had to basically replicate all the arguments the `git` command accepts itself. 

There's a workaround where we can accept extra arguments as proposed in #192 but I want to kep this cli as simple as possible

Thanks!
