### ISSUE TITLE
[Feature request]: Add --scope option to gitmoji -c command 

### ISSUE THREAD

**Issue by sirgalleto** [carloscuesta/gitmoji-cli#465]
Hello @carloscuesta! I would like to discuss a feature that came to my mind.

# Inspiration

When I'm working on a feature, my team uses certain naming convention where the ticket number is placed, for example: 

* feature/ticket-01/add-gitmoji
* fix/ticket-99/fix-bad-emoji

For different branches, I'm usually doing more than one commit, and the process of input the ticket-number as _scope of current changes_ is 1. Error prone, 2. Tedious, 3. Boring, 4. Expensive, 5. I just hate to repeat myself. 

# Proposal

Given a branch name with my team's naming convention, I can create a bash script that outputs my ticket number. 

```sh
#!/bin/sh
branch=$(git symbolic-ref HEAD)
IFS='/'
read -a strarr <<< "$branch"
echo "Book Name : ${strarr[3]} "
```

Having the ticket-number in the context I need a way to inject it into the _gitmoji-cli_, where I would like to have two options 

1. A flag in the -c command 

```sh
$ gitmoji -c --scope=$(myScript)
```

2. An environment variable. 

```sh 
GITMOJI_SCOPE=$(myScript) gitmoji -c 
```

## Personal comments

1. By adding options to receive the prompts as params, `gitmoji-cli` can be used in more different ways giving the final user more productivity and extensibility. 
2. There are certain more options to detect the scope from the branch name _for example adding a regex config_ but that comes with a solution focused in branch names, and I think the best solution is making `gitmoji-cli` more extensible. 

What do you think? 

____

I'm willing to develop this option, but first I want to confirm if you're open to add this, and what are your thoughts of the approach and implementation ideas.  

Thanks for this awesome project!

**Comment by carloscuesta** [comment]
Hey @sirgalleto 

Thanks for opening an issue!

This feature already exists! You can enable the scope prompt via the `gitmoji -g` configuration option.

See:

![Screenshot 2020-10-01 at 08 18 37](https://user-images.githubusercontent.com/7629661/94774699-b88f4a00-03be-11eb-8087-4f1b20c1c38b.png)

![Screenshot 2020-10-01 at 08 18 15](https://user-images.githubusercontent.com/7629661/94774697-b75e1d00-03be-11eb-8a19-bfdc58275a1d.png)

**Comment by sirgalleto** [comment]
Right @carloscuesta I'm already using it, and my apologies to not explain myself well. 

My point with the proposal is to skip this prompt by sending the scope via a command option/environment. Just like `git commit -m "message"` . With this change I'm able to don't repeat myself every-time I'm doing a commit where the scope is accesible programmatically . 

Example: 

```sh 
> gitmoji -c --scope "GM-123"
? Chose a gitmoji: 🎨 
? Enter the commit title: This is my title
? Enter the commit message: This is my message
```

Result: 

```
🎨  (GM-123): This is my title

This is my message
```

**Comment by carloscuesta** [comment]
I don't think we should add this to the `-c` option. This option is meant to be interactive, prompting the user for every question and and awaiting for an answer.

If you want to not "repeat yourself" and be more quick with your commits you might want to use the `hook` option which has some defaults enabled based on the arguments that are passed into the command. Maybe we can integrate this as we did at #446

**Comment by sirgalleto** [comment]
The approach at #446 is a great start point to discuss this, it accomplish in another context the same thing I want. 

If I understand correctly how #446 works is given a commit file path

1. Extracts the title from the first line. 
2. Extracts the message from the second line. 

Where in there you think we can store the scope even if you don't input the title and message. 

@adriencaccia would you mind to give us your opinion?🙏🏻

**Comment by nilskuhn** [comment]
Setting ticket / issue numbers for a feature as git scope is quite common, I would say. So in my opinion, a possibility to set a default scope and not having to type / repeat it for each commit of the feature would increase usability a lot. Environment variables like proposed in https://github.com/carloscuesta/gitmoji-cli/pull/522 would work for me just as a cli flag or a config setting defaultScope would do.

**Comment by carloscuesta** [comment]
Available in `v4.3.0` 🚀

**Comment by nilskuhn** [comment]
nice, thanks!

**Comment by sirgalleto** [comment]
@carloscuesta Super awesome 👏

**Comment by jayakornk** [comment]
@carloscuesta Thanks a lot!!
