### ISSUE TITLE
[Feature Request] GPG Sign support

### ISSUE THREAD

**Issue by gluons** [carloscuesta/gitmoji-cli#47]
Hello @carloscuesta!

I see the feature to [sign commit](https://github.com/carloscuesta/gitmoji-cli/blob/82f46b279586300d9929ab159ee13adeb07c178f/src/gitmoji.js#L205). But it is signoff commit ([`-s`](https://git-scm.com/docs/git-commit#git-commit--s)).

It should be great if I can GPG-sign commit ([`-S`](https://git-scm.com/docs/git-commit#git-commit--Sltkeyidgt)). 🙂

**Comment by carloscuesta** [comment]
@gluons In fact it should be using `-S` so i'm setting it as a default 👍

**Comment by gluons** [comment]
Thank you very much. 🙇
