### ISSUE TITLE
Signing a commit show error

### ISSUE THREAD

**Issue by motss** [carloscuesta/gitmoji-cli#48]
Hello @carloscuesta!

Unable to sign a commit in the latest upgrade like the previous version when the option of `signing a commit` has a default of `Y`.
The error will not show when not signing one.
If that's the case, the option of `signing a commit` should be default to `n`.

```
ERROR: gpg: skipped "John Doe <john_doe@gmail.com>": secret key not available
gpg: signing failed: secret key not available
error: gpg failed to sign the data
fatal: failed to write commit object
```

Issue: 

**OS**:
**gitmoji-cli -v**: 1.5.3
**Node version**: 7.10.0

**Error Message**: 

```
ERROR: gpg: skipped "John Doe <john_doe@gmail.com>": secret key not available
gpg: signing failed: secret key not available
error: gpg failed to sign the data
fatal: failed to write commit object
```

**Comment by carloscuesta** [comment]
Hey @motss this is not an error related with the CLI you should setup a GPG Key to sign your commits [Signing commits with GPG](https://help.github.com/articles/signing-commits-using-gpg/)

**Comment by darkylmnx** [comment]
@carloscuesta why is gitmoji forcing signing ? What happens if the project doesn't have any signing on the repo ? I think you might loose some users by forcing it :/

**Comment by carloscuesta** [comment]
It does not force signing, it just prompts the user @darkylmnx

**Comment by darkylmnx** [comment]
@carloscuesta well look a this : 
![image](https://user-images.githubusercontent.com/1426357/38892750-6ca7cc2e-4288-11e8-884b-c24bf5bf5c0d.png)
This is when i have added a hook and used gitmoji -c

![image](https://user-images.githubusercontent.com/1426357/38892874-c72c6182-4288-11e8-8110-0029b9f6c10d.png)

This is when I removed the hook and used gitmoji -c

**Comment by carloscuesta** [comment]
Did you try to disable the signing via the `config` option? https://github.com/carloscuesta/gitmoji-cli#config

**Comment by darkylmnx** [comment]
Nice ! Seems to work fin with this. There's still an issue with the hook though here => https://github.com/carloscuesta/gitmoji-cli/issues/93

**Comment by mixn** [comment]
@carloscuesta Disabling signed commits doesn’t work for me. I still get 

```
ERROR: error: gpg failed to sign the data
fatal: failed to write commit object
```

Shouldn’t this not be the case + it just work? Also, I’m currently working on my old machine where I am re-installing gitmoji-cli. I had this issue on my new machine already, but don’t remember how I solved it. Any idea?

**Comment by mixn** [comment]
@carloscuesta How to solve this? GPG is disabled.

**Comment by carloscuesta** [comment]
Do you have some sort of global config to sign commits? @mixn

**Comment by mixn** [comment]
It is set to false via `git config --global commit.gpgsign false`.
