### ISSUE TITLE
Windows emoji support

### ISSUE THREAD

**Issue by a2br** [carloscuesta/gitmoji-cli#488]
Hello there!
I just discovered gitmoji and its neat CLI. I installed it on my machine (Windows 10), and... well, only 10 emojis of `gitmoji -l` are supported in Windows Terminal. I looked on the internet for a solution, but nothing... Since emojis seem to be your domain, how could I get more emojis on WT? By changing the font? Is that even possible?
Thanks a lot in advance.

**Comment by carloscuesta** [comment]
Hello @a2br 

Unfortunately the last time I used a Windows machine was 11 years ago 😓 

I'm sure that you can change the font that is used to render Emojis on the Windows Terminal, however I can't give you any specific advice and insights about how to do this, maybe you can find some support on StackOverflow or sites like that!

Hope this link could help you!

https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings

Thanks! ❤️

**Comment by lmeyer** [comment]
Hi @a2br,

Did you manage to make it work ? 

Thank :)

**Comment by a2br** [comment]
I actually stopped using Gitmoji until a couple days ago, when I downloaded Fira Code on WT. It seems to work now!
