### ISSUE TITLE
ERROR: Network connection not found

### ISSUE THREAD

**Issue by mydaoyuan** [carloscuesta/gitmoji-cli#49]
Hello @carloscuesta!

Issue: 
not work , print network connection not found, but my network is work.

**OS**: 0.12.3 
**gitmoji-cli -v**:1.5.4
**Node version**:v7.7.2

➜  mytest git:(master) ✗ gitmoji bug -s
ERROR: Network connection not found - ECONNABORTED
ERROR: undefined
➜  mytest git:(master) ✗ gitmoji -u
ERROR: Network connection not found - ECONNABORTED
➜  mytest git:(master) ✗ gitmoji -v
1.5.4
➜  mytest git:(master) ✗ node -v
v7.7.2
➜  mytest git:(master) ✗ gitmoji -l
ERROR: Network connection not found - ECONNABORTED
ERROR: gitmoji list not found - undefined
➜  mytest git:(master) ✗ curl ip.cn
当前 IP：45.76.50.182 来自：日本 Vultr    // is Japan IP
➜  mytest git:(master) ✗

**Comment by carloscuesta** [comment]
Hey @mydaoyuan that's really strange are still having this issue? 

Could you `ping raw.githubusercontent.com`

**Comment by mydaoyuan** [comment]
```
➜  code ping raw.githubusercontent.com
PING github.map.fastly.net (151.101.72.133): 56 data bytes
64 bytes from 151.101.72.133: icmp_seq=0 ttl=54 time=122.519 ms
64 bytes from 151.101.72.133: icmp_seq=1 ttl=54 time=123.687 ms
Request timeout for icmp_seq 2
64 bytes from 151.101.72.133: icmp_seq=3 ttl=54 time=123.304 ms
64 bytes from 151.101.72.133: icmp_seq=4 ttl=54 time=118.238 ms
64 bytes from 151.101.72.133: icmp_seq=5 ttl=54 time=115.740 ms
^C
--- github.map.fastly.net ping statistics ---
6 packets transmitted, 5 packets received, 16.7% packet loss
round-trip min/avg/max/stddev = 115.740/120.698/123.687/3.152 ms
➜  code gitmoji bug linter -s
ERROR: Network connection not found - ECONNABORTED
ERROR: Network connection not found - ECONNABORTED
ERROR: undefined
ERROR: undefined
```

 always network error :sob:

**Comment by carloscuesta** [comment]
For some reason the fetch is failing, you can download the `gitmojis` manually just run: 

‘‘‘
nano ~/.gitmoji/gitmojis.json
‘‘‘

Then copy this contents https://github.com/carloscuesta/gitmoji/blob/master/src/data/gitmojis.json inside of that file @mydaoyuan

**Comment by tolerious** [comment]
> For some reason the fetch is failing, you can download the `gitmojis` manually just run:
> 
> `nano ~/.gitmoji/gitmojis.json`
> 
> Then copy this contents https://github.com/carloscuesta/gitmoji/blob/master/src/data/gitmojis.json inside of that file @mydaoyuan

it's not work for me.

![image](https://user-images.githubusercontent.com/2922120/68140404-b7fbf280-ff66-11e9-8eaf-d232b0ead347.png)
