### ISSUE TITLE
Problem with signed commits

### ISSUE THREAD

**Issue by franciscocandido** [carloscuesta/gitmoji-cli#492]
Hello @carloscuesta!

I'am having a problem with signed commits.

Issue:
After doing some tests, I found that the error happens when the "signed commits" option is enabled.
Just run `git add .` and `gitmoji -c`, fill all the fields and execute the commit.

**OS**: Linux Mint 20
**gitmoji -v**: 3.2.12
**Node version**: 14.15.1

**Command failed with exit code 128: git commit -S -m 🎉 init -m**:

![2020-11-22_10-16](https://user-images.githubusercontent.com/64603958/99904765-df297d00-2cab-11eb-9a3b-3a705d60d8a5.png)

**Comment by carloscuesta** [comment]
That's probably because you don't have the GPG signing set up in your computer, then you can't write signed commits.

See this comment: https://github.com/carloscuesta/gitmoji-cli/issues/334#issuecomment-600040101

Not a problem with the cli itself

Thanks for opening the issue
