### ISSUE TITLE
Add documentation for configuration options

### ISSUE THREAD

**Issue by pixelbrackets** [carloscuesta/gitmoji-cli#502]
Hello @carloscuesta, thanks for this project :+1: :100: 

Issue:
When using the configuration option `--config` the script asks “Enable scope prompt?”.

What is a »scope« in this context? What is the result when I activate this option?

**OS**: Ubuntu 20.04
**gitmoji -v**: 3.2.3
**Node version**: 10.19.0

Suggested solution: 
- Update the configuration description in the [README](https://github.com/carloscuesta/gitmoji-cli#config) (add the scope question, and shortly explain what a scope is)
- Update the commit description in the [README](https://github.com/carloscuesta/gitmoji-cli#client) and add an example GIF what happens

**Comment by pixelbrackets** [comment]
The README already contains a GIF with all kinds of commands – This could imho be split and reduced to a search example and a commit example. Please much slower play speed though ;)

**Comment by carloscuesta** [comment]
Hey @pixelbrackets 

Thanks for opening an issue. You're right the "scope" option is not really documented since we're assumming prior knowledge on the docs and the feature that's not great!

Feel free to send a PR! ❤️

**Comment by carloscuesta** [comment]
The GIF is really outdated I will probably make a new one
