### ISSUE TITLE
[Development] Cannot install fresh project

### ISSUE THREAD

**Issue by Jeremie-Chauvel** [carloscuesta/gitmoji-cli#506]
Hello @carloscuesta!

while installing the project locally to work on an issue, I found stumbled upon the following issue during `yarn install`:

Issue:
- Clone fresh project
- `yarn install`
I tested with and without global gitmoji-cli installed

**OS**: linux
**gitmoji -v**: https://github.com/carloscuesta/gitmoji-cli/commit/394de23788a93b3e2bc09c4826244528f3ffb920
**Node version**: v14.15.1

**Error Message**:

![image](https://user-images.githubusercontent.com/28385941/101405958-1ff2da00-38d9-11eb-8a8d-50cee584d695.png)

Might look into it while working on the other issue, however I wanted to warn you as soon as possible as it might deter new contributors.

**Comment by carloscuesta** [comment]
Oh! That's related with a postInstall hook I made.

You can install the dependencies using the following command:

`yarn install --ignore-scripts`

I'll fix this on the meantime

Thanks for reporting it ☺️
