### ISSUE TITLE
Don't check for the latest emojis every run

### ISSUE THREAD

**Issue by Matt-Gleich** [carloscuesta/gitmoji-cli#508]
Hello @carloscuesta!

Issue:

Every time I run `gitmoji commit` it takes a second or two to show the selection menu. I assume that this is because it gets the latest emojis on every run. What do you think of the following process instead?

![Screen Shot 2020-12-07 at 7 55 28 PM](https://user-images.githubusercontent.com/43759105/101425399-7c4dfd80-38c9-11eb-8841-7d6865945ea9.jpg)

An easier fix would be to provide an option to not update on every run and allow the user to update manually with another command like `gitmoji update`.

**OS**: macOS Big Sur 11.0.1
**gitmoji -v**: 3.2.12
**Node version**: v15.3.0

**Error Message**:

N/A

**Comment by carloscuesta** [comment]
Hey @Matt-Gleich 

Not really. The gitmojis are fetched once and cached into your computer. To update them you need to use the update command

Thanks for opening the issue!

**Comment by Matt-Gleich** [comment]
Thank you for the quick response! Do you think the slow startup time is because this is a node application? If so do you mind if I make this CLI in golang so it is faster?

**Comment by carloscuesta** [comment]
I don't know why you can have the little delay on starting up the command. No one has complained about it. Instead of remaking the whole project to Golang you can try to investigate and provide more information to your use-case to see if we can improve it
