### ISSUE TITLE
Gitmoji stages all files during commit phase

### ISSUE THREAD

**Issue by nico29** [carloscuesta/gitmoji-cli#51]
Hello @carloscuesta!

Issue: 

I dunno if this is just me doing this, but sometimes I modify several files but wanna commit them appart. So I stage some of them and then I run `gitmoji -c`. However, during its commit stage, the cli runs `git add .` and as a consequence all my modified files end up in the current commit.

Not a big deal though 😺 

**OS**: Windows 10
**gitmoji-cli -v**: 1.5.4
**Node version**: 8.0.0

Thank you ! :v:

**Comment by carloscuesta** [comment]
Hey @nico29 

By default the client adds all the files, you can disable this feature using the config option :+1: 

See [https://github.com/carloscuesta/gitmoji-cli#config](gitmoji config)

**Comment by nico29** [comment]
Missed that ! Sorry !
