### ISSUE TITLE
commit message code injection

### ISSUE THREAD

**Issue by KevinHivert** [carloscuesta/gitmoji-cli#52]
Hello @carloscuesta :sunglasses:!

# Issue: 

__Step to reproduce__

```
? Enter the commit title: Fixing \`yarn run build\` script
```

Or whatever bash command line you insert between \`. Other example :

```
$ gitmoji -c
? Choose a gitmoji: ✅  - Adding tests.
? Enter the commit title: `echo "foobarbaz"`
? Enter the commit message: 
? Issue / PR reference: 
? Signed commit: Yes
[dev 709eefb] :white_check_mark: foobarbaz
```

__What is expected__

A commit message with the selected emoji and text above

__Actual Behavior__

The \` are removed from the commit message and the command is executed with the output printed inside the commit message.

**OS**: Archlinux
**gitmoji-cli -v**: 1.5.5
**Node version**: v7.10.0

**Comment by carloscuesta** [comment]
Thanks for reporting the issue I'm working on a fix @KevinHivert
