### ISSUE TITLE
Option to skip title and message prompt ?

### ISSUE THREAD

**Issue by momsse** [carloscuesta/gitmoji-cli#534]
Hello @carloscuesta!

Thanks for the great job done with gitmoji and this cli ❤️

Is it possible to add support for an option that will skip `title` and `message` prompt when already filled by the hook (thanks to https://github.com/carloscuesta/gitmoji-cli/pull/446) ?

Issue:

Basically when I run the following command:

```bash
commit -m "title" -m "message"
```

Would love to not have to double enter to skip the already filled `title` / `message` ❤️

<img width="655" alt="Capture d’écran 2021-01-30 à 21 10 39" src="https://user-images.githubusercontent.com/1344228/106366987-b4a90f80-633f-11eb-965a-36f53dc68909.png">

**OS**: Mac
**gitmoji -v**: 3.2.18
**Node version**: 12.18.0

**Comment by carloscuesta** [comment]
Hey @momsse, thanks for opening an issue 😊 

I totally understand your concern, whenever you're prefilling those two questions with the `title` and `message` it doesn't makes any sense to ask for them on the cli. 

However, I think that then prompting the cli only for the gitmoji then it's a "waste" of time because you should already decide your gitmoji before your commit message, so I don't really see the point of using the cli in this way. It doesn't adds any real value to the user

We can try to implement the skipping feature but I think that the ☝🏼 problem is something bigger to consider!

What do you think?

**Comment by momsse** [comment]
Thanks for the reply,

> However, I think that then prompting the cli only for the gitmoji then it's a "waste" of time because you should already > decide your gitmoji before your commit message, so I don't really see the point of using the cli in this way. It doesn't adds any real value to the user

If I always remember some emoji by heart (like `:bug:`, `:sparkles:`). Some of them are uncommon enough that before suing this cli I was wasting my team searching in https://gitmoji.dev the correct one to use and that's actually the value (for me) of that cli. Entering the correct keywords for having the correct gitmoji.

Another great feature (for me) would be to dismiss completely the hook when it detect that we already enter the correct gitmoji :-)

But I completely understand that perhaps my usage is not the one expected by this cli.

Thanks you anyway for the great work and the time responding me :-)

**Comment by carloscuesta** [comment]
It makes sense! If we implement this feature then we should be removing the prefill one since the questions are going to be skipped right?

**Comment by momsse** [comment]
> It makes sense! If we implement this feature then we should be removing the prefill one since the questions are going to be skipped right?

Yes. But since it's opinionated it would be great to ask the user if he want to use the feature with `gitmoji --config` nope ?

```
➜ gitmoji --config
? Skip prompt for title and message if they are already filled (Y/n)
```

**Comment by carloscuesta** [comment]
Sounds good! Would you like to build a PR to implement the feature?

**Comment by momsse** [comment]
I will give a try yes
