### ISSUE TITLE
$ gitmoji -c ERROR: This directory is not a git repository.

### ISSUE THREAD

**Issue by chrisj-skinner** [carloscuesta/gitmoji-cli#55]
Hello @carloscuesta!

Issue: 
$ gitmoji -c

**OS**: windows 10 VSC
**gitmoji-cli -v**:  1.5.6
**Node version**: v6.9.2

**Error Message**: ERROR: This directory is not a git repository.

![imo](https://user-images.githubusercontent.com/5794048/27331206-6b34f522-55b4-11e7-97bc-99e02dc31723.PNG)

**Comment by carloscuesta** [comment]
Hey @chrisj-skinner I'm not having problems on a Mac OS X, do you have a `.git` folder inside your directory? Could you try creating another repo and see if the problem persists?

**Comment by nico29** [comment]
Hello. I Have the same issue, this happen when I try to commit inside a subfolder of a git repo.

```
. <- here .git
└── templates
    └── nmn2
        ├── 0
        │   ├── config.properties.sample
        │   ├── docker-compose.yml
        │   └── rancher-compose.yml
        ├── 1 <- I wanna commit here
        │   ├── config.properties.sample
        │   ├── docker-compose.yml
        │   └── rancher-compose.yml
        ├── catalogIcon-wap.png
        └── config.yml
```

I'm running `gitmoji-cli` v 1.5.7

**Comment by carloscuesta** [comment]
Hey @nico29 that makes sense! Because the .git folder is being searched on the current directory

**Comment by nico29** [comment]
Yep sure, but I think @chrisj-skinner is trying to do the same 😸

**Comment by carloscuesta** [comment]
Yep! I will take a look :+1:

**Comment by chrisj-skinner** [comment]
Yes, `src/app` is a sub dir of `olr-app` and I'm trying to commit to the sub dir
