### ISSUE TITLE
Feature request: read core.hooksPath from git config during `gitmoji -i`

### ISSUE THREAD

**Issue by flo-sch** [carloscuesta/gitmoji-cli#577]
Hello @carloscuesta!

Issue:

`gitmoji -i` currently creates a `prepare-commit-msg` file under the hardcoded `.git/hooks` path, which is the default path for git hooks.
However, this path can be configured `git config --set core.hooksPath path/to/hooks/folder` and this is what for instance [husky v6 started to do](https://github.com/typicode/husky/issues/943).

Would it be possible to create that file at the local config path instead, accessible by running `git config --get core.hooksPath`? (using  [child_process.spawnSync](https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options) or such perhaps?)

**OS**: Mac OS 11.2.3
**gitmoji -v**: 3.3.1
**Node version**: 14.16.1

**Comment by carloscuesta** [comment]
Yes! This is much better than assuming the local default hooks directory

Will try to take a look at this but if you want to help feel free!

**Comment by flo-sch** [comment]
I can give it a quick try this week I think

**Comment by carloscuesta** [comment]
Thanks for the help @flo-sch

**Comment by rushilsrivastava** [comment]
@carloscuesta Was #578 bundled with v3.4.0? I looked through the package posted on NPM (see the hook file on [unpkg](https://unpkg.com/browse/gitmoji-cli@3.4.0/lib/commands/hook/hook.js)) and I don't think #578 has been merged in.

The release notes mention that this was intended as well.

**Comment by rushilsrivastava** [comment]
The release published by Github actions seems to be working fine, I think the version published to NPM and Brew have a different version uploaded.

**Comment by carloscuesta** [comment]
That's really weird 🤔 Going to republish now

**Comment by carloscuesta** [comment]
Republished and fixed at 3.4.1 🎉

**Comment by carloscuesta** [comment]
Turns out I forgot to execute the `build` script before publishing 😅. I automated this on a PR to never forgot it again
