### ISSUE TITLE
Can't install hooks on windows

### ISSUE THREAD

**Issue by JulioC** [carloscuesta/gitmoji-cli#58]
Hello @carloscuesta!

When trying to run `gitmoji -i` on Windows I get the error and the hook don't get installed.

**OS**: Windows 10
**gitmoji-cli -v**: 1.5.8
**Node version**: v7.7.4

**Error Message**: 

```
ENOENT: no such file or directory, open 'E:\project\undefined\.git\hooks\prepare-commit-msg'
```

**Extra Info**:

I noticed the path is defined using process.env.PWD, so when I tried getting the value for that:

```
PS E:\project> echo $PWD

Path
----
E:\project
```

**Comment by carloscuesta** [comment]
Hey @JulioC as you can see the `process.env.PWD` is `undefined` that's why it's not creating the hook succesfully, I think that's a common bug on Windows, let me take a look 👀
