### ISSUE TITLE
Garbled rendering

### ISSUE THREAD

**Issue by Monkeyman520** [carloscuesta/gitmoji-cli#581]
Hello @carloscuesta!

gitmoji renders garbled characters in Windows power shell
Issue:

![image](https://user-images.githubusercontent.com/55369727/115650597-1df75800-a35c-11eb-8cf5-543ad90de67c.png)

**OS**:Windows 10 2004
**gitmoji -v**:3.4.0
**Node version**:10.21.0

**Error Message**:

**Comment by WebKenth** [comment]
@Monkeyman520  this could be your font. It doesn't look like a monospace font with propper emoji support, Which font are you using? it looks neat ;) 

This issue somewhat matches my issue from:
From https://github.com/carloscuesta/gitmoji
Hello @carloscuesta sunglasses! ( You asked my to move it ;) )

The list would look nice if every line had the same consistent markup, however some lines are missing spaces giving a confusing view

🚧 - :construction: - Work in progress.
💚 - :green_heart: - Fix CI Build.
⬇️ - :arrow_down: - Downgrade dependencies.
⬆️ - :arrow_up: - Upgrade dependencies.
📌 - :pushpin: - Pin dependencies to specific versions.
👷 - :construction_worker: - Add or update CI build system.
📈 - :chart_with_upwards_trend: - Add or update analytics or track code.
♻️ - :recycle: - Refactor code.
➕ - :heavy_plus_sign: - Add a dependency.
➖ - :heavy_minus_sign: - Remove a dependency.
🔧 - :wrench: - Add or update configuration files.
🔨 - :hammer: - Add or update development scripts.
🌐 - :globe_with_meridians: - Internationalization and localization.
✏️ - :pencil2: - Fix typos.
As you can see from the image there are missing white spaces to keep the list consistent :)
image

![image](https://user-images.githubusercontent.com/13419123/115850727-785ceb00-a426-11eb-841c-f3cf43a001ca.png)

**Comment by carloscuesta** [comment]
Hey @Monkeyman520 this seems an issue with the font that you're using on your Terminal, I don't have a Windows machine so sadly I won't be able to help much further on this issue :(

Could you open another issue on this repo @WebKenth since we could treat this as something independent from this question!

Thanks <3
