### ISSUE TITLE
Error after update to 3.4.1 : Command failed with exit code 1: git config --get core.hooksPath

### ISSUE THREAD

**Issue by wijourdil** [carloscuesta/gitmoji-cli#589]
Hello @carloscuesta!

**Issue:**
I have just updated the gitmoji-cli from version 3.4.0 to 3.4.1, and now I have an error message when I do a commit with the command `gitmoji -c`.
The commit is well created, and I can push it to my repository, so I'm not blocked but the error appears each time I do a commit with gitmoji-cli.
I have updated the tool with the command: `npm i -g gitmoji-cli`

**OS**: macOS Big Sur 11.2.3
**gitmoji -v**: 3.4.1
**Node version**: node: v15.14.0 / npm: 7.10.0
**git version**: git version 2.24.3 (Apple Git-128)

**Error Message**:
```
Error: Command failed with exit code 1: git config --get core.hooksPath
    at makeError (/usr/local/lib/node_modules/gitmoji-cli/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/gitmoji-cli/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async getAbsoluteHooksPath (/usr/local/lib/node_modules/gitmoji-cli/lib/utils/getAbsoluteHooksPath.js:17:7)
    at async isHookCreated (/usr/local/lib/node_modules/gitmoji-cli/lib/utils/isHookCreated.js:18:22)
    at async withClient (/usr/local/lib/node_modules/gitmoji-cli/lib/commands/commit/withClient/index.js:26:9) {
  shortMessage: 'Command failed with exit code 1: git config --get core.hooksPath',
  command: 'git config --get core.hooksPath',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Screenshot**:

<img width="819" alt="error" src="https://user-images.githubusercontent.com/12596207/116096780-d9e0bc00-a6a9-11eb-8f27-60d74e7f7743.png">

**Comment by carloscuesta** [comment]
Hey @wijourdil thanks for opening an issue, this is related with #578 will try to take a look today!

Hey @flo-sch could you take a look at this too?

**Comment by flo-sch** [comment]
Hi @wijourdil, just so I know, what output do you get when you directly call `git config --get core.hooksPath`?

The git version should not be a problem (btw @carloscuesta should we somehow handle that?) but it might be something else I missed from the git doc 🤔

**Comment by wijourdil** [comment]
Hi !

When I execute this command I have no output, and the return value is `1`

<img width="405" alt="Screenshot 2021-04-26 à 18 47 53" src="https://user-images.githubusercontent.com/12596207/116120532-ea9c2c80-a6bf-11eb-9722-bef27cf0bf9d.png">

**Comment by wijourdil** [comment]
I solved the issue by creating a folder `~/.git/hooks/` and then I have edited the configuration with the command
`git config --global --edit` and added this section : 
```
[core]
        hooksPath = ~/.git/hooks
```

I don't know if it's just a workaround or the "correct way" to fix it, but now I don't have the error anymore 🤷

**Comment by flo-sch** [comment]
That looks more like a workaround: according to the docs of `git config --get`, it seems that the exit code of 1 is expected when the key is not found, but I can reproduce the warning from gitmoji in any way...
(Tried several versions of Node and different versioning scenarios)

(Setting the config like you did for sure will fix the problem for you)

@carloscuesta unless you see a better way, we might as well just silently try/catch the `git config --get` call inside `getAbspkuteHooksPath` and default to `$GIT_DIR/hooks` when it fails (current default behavior)

**Comment by carloscuesta** [comment]
🤔  That's weird, the `~/.git/hooks/` things is clearly a workaround and we shouldn't be using this as a solution

[According to this](https://github.com/git/git/blob/311531c9de557d25ac087c1637818bd2aad6eb3a/Documentation/RelNotes/2.9.0.txt#L127-L128) the `core.hooksPath` configuration was introduced at git `2.9` so it's not a git version problem

**Comment by carloscuesta** [comment]
I had been able to reproduce the issue:

1. Create a new directory.
2. Initialise a git repository.
3. Add a dummy file
4. Commit using `gitmoji -c` option

**Comment by carloscuesta** [comment]
Working on a fix!

**Comment by flo-sch** [comment]
Nicely done :)

**Comment by carloscuesta** [comment]
Thanks for the help @flo-sch and @wijourdil

**Comment by wijourdil** [comment]
Great, thank you ! 👏 😄
