### ISSUE TITLE
Failed to update to 4.1.0

### ISSUE THREAD

**Issue by VGMSoft** [carloscuesta/gitmoji-cli#606]
Hello @carloscuesta!

Issue:
When trying to update to gitmoji 4.1.0, the update fails. It seems it's a naming issue.

**OS**: BigSur
**gitmoji -v**: 4.0.0
**Node version**: 11.2.11

**Error Message**:
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/gitmoji-cli
npm ERR! dest /usr/local/lib/node_modules/.gitmoji-cli-i0trtzkW
npm ERR! errno -66
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/gitmoji-cli' -> '/usr/local/lib/node_modules/.gitmoji-cli-i0trtzkW'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/virgileguglielmi/.npm/_logs/2021-05-23T12_30_17_550Z-debug.log

**Comment by carloscuesta** [comment]
Hello!

Node version 11 is no longer supported, the minimum required version to use this package is Node v12

**Comment by VGMSoft** [comment]
Hi Carlos,

I’m currently working with node 14.16.1.
11.2.11 is my Angular version....
Should I rename my file as said without problems...?

Virgile Guglielmi

**Comment by carloscuesta** [comment]
Try to uninstall the cli and install it again
