### ISSUE TITLE
As a user, when I `gitmoji -c` with changes not staged, I get frustrated when I get an error after typing my message knowing I will need to type it again

### ISSUE THREAD

**Issue by vhoyer** [carloscuesta/gitmoji-cli#610]
Hello @carloscuesta!

As a user, when I `gitmoji -c` with changes not staged, I get frustrated when I get an error after typing my message knowing I will need to type it again.

Issue:

My main problem with this is that sometimes I forget to `git add` the changes before trying commiting, so I call `gitmoji -c` and happily type my commit message, and when I'm done typing, I get a non-user-friendly error saying that I had nothing to commit, the problem here is that I don't wanna type my message again.

So my proposal would be either:
- save a cached version of what the user typed if there is an error with git, so that when I get an error, I type `gitmoji -c` again and the message is pre-filled, I can just press enter or I can even change it if it's not what I want; or
- check before beginning the inquiry If there are changes to commit, and if there aren't any changes to commit, just throw a preemptive error so I don't have to type anything to begin with.

**OS**: Ubuntu 16.04.7 LTS 16.04 xenial
**gitmoji -v**: 3.2.16
**Node version**: v14.15.0

**Error Message**:

No error, it's just a behavior I want to change :D

**Comment by carloscuesta** [comment]
Hey @vhoyer!

I'm not sure if we should handle this on the cli, as it's more a git error than a cli one

**Comment by vhoyer** [comment]
This is a git error, but this is also an poor UX from the CLI, because this same error doesn't happen when using git alone

**Comment by carloscuesta** [comment]
If you try to commit without previously add anything to the staged area then you'll get the same error 🤔

**Comment by carloscuesta** [comment]
Uh but the error you get is worse and way more scary 😂 😱 

<img width="955" alt="Screen Shot 2021-08-04 at 20 18 08" src="https://user-images.githubusercontent.com/7629661/128233596-5cdb7ecd-2add-49d6-98a1-29a5e76f3ada.png">

**Comment by carloscuesta** [comment]
I think that a better approach would be to show and print the errors in a better way like this:

<img width="649" alt="Screen Shot 2021-08-04 at 20 27 38" src="https://user-images.githubusercontent.com/7629661/128234942-de89494c-6529-4d67-a60f-ff373969b19f.png">

Because otherwise we would need to potentially cover more errors and use cases and also is better for the user to see this kind of errors as "eating" the stdout of them could lead to a confusing situations where something happened and you don't know exactly what failed, for example in #291

**Comment by vhoyer** [comment]
Ok, fair, better error output would be also great, but the point that I'm trying to make here is that the bad experience I get from the gitmoji-cli comes from the fact that if an error occurs I will lose the message I just wrote, and this is the part that I don't like.

when I'm using stand alone git, I write my commits with `git commit -m"bla bla bla"` because of the chance of there being an error, so I can just go back to the recent commands run so I can run the same commit after fixing the error. But with using the cli util, I just have to either type it again, or copy from the terminal history, which both options are really kinda bothersome :/

**Comment by carloscuesta** [comment]
I see! In the release `4.3.0` we introduced some flags for prefilling your commits:

https://github.com/carloscuesta/gitmoji-cli#options

So if you use the command like this: 

```
$ gitmoji -c --title="Commit title"
```

Then you will be able to go back and maintain the value in the prompt 😊

**Comment by vhoyer** [comment]
Oh, I guess it's my fault for not reading the changelog... Thanks 😊

**Comment by carloscuesta** [comment]
No worries! Published `4.5.0` with this improvement 👍🏼
