### ISSUE TITLE
[Feature Request] Add cherry pick emoji and version on gitmoji -c

### ISSUE THREAD

**Issue by girordo** [carloscuesta/gitmoji-cli#619]
Hello @carloscuesta!

I was looking for an a representative emoji for cherry picking so nothing better than the cherries 🍒 
It would be nice if we have this option

If I'am doing something wrong please desconsider this

**Comment by carloscuesta** [comment]
Hey @girordo 

The emoji suggestions should be opened on the gitmoji repository!

Thanks ☺️
