### ISSUE TITLE
Error during commit.

### ISSUE THREAD

**Issue by t-p-l-k** [carloscuesta/gitmoji-cli#62]
Hello @carloscuesta!
Thanks in advance.

I'm constantly getting an error when trying to commit changes. Also when I use `git add --patch` all files are getting staged automatically after failing to commit.

Issue started appering after I updated to 1.6.0. there's no `.git/index.lock` file (it's stated in error message to delete it manually). Rebooting, reinstalling `gitmoji-cli` or trying to perform actions in a new repo don't help.

Steps to reproduce:
```sh
mkdir test && cd test && git init
touch test_file
git add .
gitmoji
```

**OS**: Windows 10
**gitmoji-cli -v**: 1.6.0
**Node version**: 7.9.0

**Error Message**: 
```
ERROR: fatal: Unable to create 'project/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

**Comment by t-p-l-k** [comment]
I'll investigate whether it's a local issue affecting only me and close the issue if it is. Feels like it is, had some issues with npm config a few days ago.

But I thought that it'd be good to know if someone's experiencing the same problem.

**Comment by carloscuesta** [comment]
Hello @t-p-l-k 

As you say this is probably a local issue but sometimes appears as seen on https://github.com/carloscuesta/gitmoji-cli/issues/9#issuecomment-282562142

**Comment by t-p-l-k** [comment]
@carloscuesta Okay, thanks, I'll try to use fix https://github.com/carloscuesta/gitmoji-cli/issues/9#issuecomment-282562142.
