### ISSUE TITLE
Git add all, disable option

### ISSUE THREAD

**Issue by khaosdoctor** [carloscuesta/gitmoji-cli#63]
Hello @carloscuesta!

Something is been going on with my version. Even when I disable automatic `git add .` this setting seem not to persist. My idea is to transform it into an option `-a`, if set then it'd add everything, otherwise it'd just commit.

Issue: 
Even when I disable automatic `git add .` this setting seem not to persist

**OS**: MacOS Sierra
**gitmoji-cli -v**: 1.6.0
**Node version**: 8.4.0

**Comment by carloscuesta** [comment]
Hey @khaosdoctor 

Seems like there's a bug let me take a closer look

**Comment by khaosdoctor** [comment]
Yeah! Ok then! I will download it and test it out here ;)
