### ISSUE TITLE
Real emoji in git commit message

### ISSUE THREAD

**Issue by jeyraof** [carloscuesta/gitmoji-cli#630]
Hello @carloscuesta!

**Question**:

Is there any reason for having choice to use not real emoji but replacable word-wrap?
for example, i want to use real emoji on git commit message:

```
💬 Something commit message~~
```

But gitmoji cli generate it like:
```
:speech_balloon: Something commit message~~
```

**OS**: mac bigsur
**gitmoji -v**: 4.1.0
**Node version**: v16.4.0

**Comment by carloscuesta** [comment]
Hey! @jeyraof 

You can configure this behaviour using the `gitmoji -g` configuration option.

There's a prompt that will allow you to choose between the shortcode or the actual emoji.

The reason behind this was to be able to use the shortcode to favour the readability on certain terminals that do not support Emojis!

**Comment by jeyraof** [comment]
@carloscuesta Wow. Thank you for your description about detail things!
I have set it!
