### ISSUE TITLE
Unable to create .git/index.lock

### ISSUE THREAD

**Issue by svenlombaert** [carloscuesta/gitmoji-cli#64]
Hello @carloscuesta 😎!

Since a while now, every time I commit (I have the pre-commit hook installed), after it, I get this message:

```
ERROR: fatal: Unable to create '/Projects/pathname/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```
I've tried removing and installing the pre-commit hook, removed gitmoji-cli completely and updated to the most recent version - nothing helps. I encounter the same problem without pre-commit hook and just using the gitmojicommand. When I just commit normally (without gimoji) everything works fine 👌 .

Any ideas?

KR

**Comment by Seaony** [comment]
I also met the same problem, did you find the solution?

**Comment by carloscuesta** [comment]
Related with #9 #10 #62

**Comment by svenlombaert** [comment]
MacOS Sierra, Version 10.12.6 (16G29)

Thanks!

**Comment by samirdhebar** [comment]
I also am having the same issue on Linux regarding this commit issue. I reviewed the earlier fix but sadly to no avail :cry:

**Comment by LBreda** [comment]
Same here, on Linux. The lockfile doesn't actually exist.

**Comment by gluons** [comment]
Me too. On Kubuntu 17.04. It happened sometime.

![_002](https://user-images.githubusercontent.com/4688092/30250443-9556e28e-9678-11e7-96aa-0ff90301f577.png)

**Comment by gluons** [comment]
Did anyone found the cause of this problem?  
I frequently face this problem but I can't find why it happened. 🤔  
Try to find `index.lock` file in my `.git` folder but it doesn't exist.  😵

**Comment by carloscuesta** [comment]
As the error messages says, this problem comes from: 

> Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

I've been investigating and I haven't found a solution yet. It's really weird because it's hard to reproduce the error. IMHO I think the issue is related with use of the `hook` option

https://github.com/carloscuesta/gitmoji-cli/blob/ea99b5166c2d642d72be7f536d69127cecb99409/src/gitmoji.js#L108

https://github.com/carloscuesta/gitmoji-cli/blob/ea99b5166c2d642d72be7f536d69127cecb99409/src/gitmoji.js#L112

It really never happened to me, at least with `gitmoji-cli`.  I've faced this issue (when cancelling a pull, commit etc.) while using the basic `git` command and I've fixed it by running: 

```bash
rm -rf .git/index.lock
```

Any help is appreciated! 👍

**Comment by gluons** [comment]
> it's hard to reproduce the error

Agree. I can't predict when it'll happen. I happen randomly. 😴

**Comment by carloscuesta** [comment]
@gluons @svenlombaert @Seaony @samirdhebar @LBreda 

I've created at `lab-fix-index-lock` to test out some fixes, could you please try to install the cli from this branch and see if the problem persists?

```
$ npm i -g git://github.com/carloscuesta/gitmoji-cli.git#lab-fix-index-lock
```

**Comment by gluons** [comment]
@carloscuesta  **Off topic:** New version no longer has default CLI action? 😅

![_004](https://user-images.githubusercontent.com/4688092/30785264-af8f29e2-a18e-11e7-87a5-6da10d5bec23.png)

**Comment by carloscuesta** [comment]
@gluons No

Read the release changelog at https://github.com/carloscuesta/gitmoji-cli/releases/tag/v1.7.0

**Comment by gluons** [comment]
Oh! Sorry. The fresh version. I haven't read it. 😅

**Comment by gluons** [comment]
It still happen. 😢

![default](https://user-images.githubusercontent.com/4688092/30822371-b1865ed6-a252-11e7-9bb1-80921e28c12b.png)

**Comment by RumbleFrog** [comment]
An interesting thing is that if you create index.lock manually and try to commit, it'll emit the error message twice.

**Comment by RumbleFrog** [comment]
I'm constantly getting this specific error on this repo: https://github.com/sbpp/sbpp.github.io

But not any others, not sure what's different

**Comment by ppartarr** [comment]
If you are using an IDE try disabling source control and refreshing

**Comment by martinfengshenxiang** [comment]
I'am also don't have the index.lock file.
when I am running git add --all & git commit -m 'add some file',  get the error.
But after I running each command seperately, problem solved!
I runned:
`
git add --all
git commit -m 'add some file'
`
just like magic😊

**Comment by muwoo** [comment]
@martinfengshenxiang yeah! That's true! `gitmoji -c` whill running `git add . && git commit -m ''` default.
so I run `gitmoji -g` and choose N to  close `git add .`

![image](https://user-images.githubusercontent.com/21073039/42430214-58514cb8-8370-11e8-8f2d-fc858b0378e5.png)

After that, just fine.

**Comment by svchraghava** [comment]
I also face the same issue in windows. 

![image](https://user-images.githubusercontent.com/37681830/43360089-dc5b8f66-92e1-11e8-9b93-236a60592a50.png)

**Comment by JSteunou** [comment]
> I'am also don't have the index.lock file.
> when I am running git add --all & git commit -m 'add some file', get the error.
> But after I running each command seperately, problem solved!
> I runned:
> `git add --all git commit -m 'add some file'`
> just like magicblush

I think that's because it should be `git add --all && git commit -m 'add some file'` with a double `&` if you wanna run the cmds separately

**Comment by ZakirBalti** [comment]
try to delete the Exist lock file then issue will be resolve
rm -f .git/index.lock

**Comment by dudongdaoqi** [comment]
@muwoo Thanks！ It works for me！

**Comment by mrguilima** [comment]
I was stuck with this message for some time:

error: could not close '/home/lima/work/geantx/.git/index.lock'
fatal: unable to write new index file

In my case, I had ran out of quota.  Once I cleaned up some files in other areas, git was back to normal!
I hope this is useful for others.
