### ISSUE TITLE
Print failed git command

### ISSUE THREAD

**Issue by capsuleman** [carloscuesta/gitmoji-cli#680]
Hello @carloscuesta!

Frequently, on my projects, commit fails (sometime I forget to add files, other times pre-commit hooks return error).
It would be nice to have the git commit command print to just copy / paste it the next times. 

Issue:

**OS**:
**gitmoji -v**:
**Node version**:

**Error Message**:

**Comment by carloscuesta** [comment]
Why not using arrow up key instead? It should be faster than copy pasting right?

**Comment by capsuleman** [comment]
When I use `gitmoji -c`, I do not provide any other parameters and enter gitmoji and message in the cli. If I use arrow up key, I can not find again the parameters I filled previously.
