### ISSUE TITLE
How do I specify a proxy when updating the gitmojis list?

### ISSUE THREAD

**Issue by Hccake** [carloscuesta/gitmoji-cli#688]
Hello @carloscuesta!

How do I specify a proxy when updating the gitmojis list?

I saw the corresponding PR, but did not find the corresponding usage document.

**Comment by carloscuesta** [comment]
Hey! It's explained in the [configuration command options](https://github.com/carloscuesta/gitmoji-cli#options-1):

> <img width="857" alt="Screen Shot 2021-09-14 at 13 27 43" src="https://user-images.githubusercontent.com/7629661/133249585-f40c4df3-a379-4b12-9a7c-fb082588273c.png">
