### ISSUE TITLE
Allow filter by conventional commit type

### ISSUE THREAD

**Issue by eliutgon** [carloscuesta/gitmoji-cli#689]
Hello @carloscuesta!

Allow filtering by type, e.g. **feat, refactor, fix**

**Comment by carloscuesta** [comment]
Hey @eliutgon

Thank for opening an issue!

I think that gitmoji and conventional commits are different things so I would prefer to not build a filter like that for this specific reason 😊

The cli already has a filter to search for emojis, if you feel this is not useful at all you can try conventional commits or other conventions!
