### ISSUE TITLE
commit make terminal freeze

### ISSUE THREAD

**Issue by kamontat** [carloscuesta/gitmoji-cli#71]
Hello @carloscuesta!

my terminal hang/freeze when I use `gitmoji -c`

#### Issue: 
my step is 
1. select emoji
2. enter commit title 
3. let message empty
4. let issue empty
5. `HANG`

example result
```
? Choose a gitmoji: 🔥  - Removing code or files.
? Enter the commit title: hello world
? Enter the commit message:
? Issue / PR reference:
```

![screen shot 2560-10-18 at 23 06 07](https://user-images.githubusercontent.com/14089557/31729335-f1ec41ee-b458-11e7-8234-32d04f754b7e.png)
**gitmoji-cli -v**: 1.8.1
**Node version**: v8.5.0

**Comment by carloscuesta** [comment]
Did you used the hook init method before? If it’s true that’s the issue you should delete the hook file.

However, you can try the cli on a fresh git repository?

Create a new directory, run `git init` add some random files and try to use the -c option. It should work as expected

**Comment by kamontat** [comment]
Try but still freeze.

**Comment by carloscuesta** [comment]
It's working fine for me @kamontat 

![screen shot 2017-10-21 at 13 28 21](https://user-images.githubusercontent.com/7629661/31851319-b8bb6118-b663-11e7-80c7-e50346fbba33.png)

**Comment by kamontat** [comment]
After I enter Issue and pr, what is script doing? Just call commit?

**Comment by carloscuesta** [comment]
https://github.com/carloscuesta/gitmoji-cli/blob/eac2b612071c302fc1a10222780d3084b7294627/src/gitmoji.js#L117-L143
