### ISSUE TITLE
Sort emojis list by usage 

### ISSUE THREAD

**Issue by codingedgar** [carloscuesta/gitmoji-cli#719]
Hello @carloscuesta!

What about showing the last 7 emojis used instead of the first 7 statically?

(could help implementing it)

**Comment by carloscuesta** [comment]
Hey @codingedgar that's a great idea! 

Sorting the emojis that appear on the list based on the usage preference ✨ 

Feel free to implement it!

**Comment by carloscuesta** [comment]
Hey!

I'll close this issue as hasn't received any more updates since a year ago! 😊
