### ISSUE TITLE
Can this auto close issue in github by close keyword?

### ISSUE THREAD

**Issue by kamontat** [carloscuesta/gitmoji-cli#72]
Hello @carloscuesta!

closing-issues: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by carloscuesta** [comment]
Yes it’s actually supported, if you reference the issue with the number and then on the commit message you should put the keyword like “Closes”

**Comment by kamontat** [comment]
Oh I have tested, and It work fine. Thank you
