### ISSUE TITLE
Choose gitmojis by number and shortcode

### ISSUE THREAD

**Issue by codingedgar** [carloscuesta/gitmoji-cli#720]
Hello @carloscuesta!

So far choosing a gitmoji is done by arrows or search.

When doing arrows i cannot avoid thinking "it could be a number from 1 to 7 to pick one of the 7 emojis shown"

And with search I'm not 100% assertive I'm searching for the right keyword if i want to select the second emoji ⚡ and type `i` then ♿ is shown, then `im` and 🔍 is shown, is not after `imp` than ⚡ is the first show, but also, `improve` and `performance` show multiple emojis, which is a perfect fuzzy search. If i knew the name of the emoji tho, and type `zap` then it shows unambiguously and the though process is much more straight forward but the shortcode is not shown anywhere it cound be useful for learning the emojis (also the webpage seems to use a diff algo for searching)

**Comment by carloscuesta** [comment]
Hey @codingedgar if we implement #719 adding a number here could be confusing as the order can potentially change based on the usage of the emojis.

Instead what I would prefer is a more intelligent search criteria so we can filter emojis easily!

**Comment by codingedgar** [comment]
Sorry, I don't mean assign a number to an emoji, but to the options shown, so the first item is always 1, and the second is 2 and so on, to make selecting an emoji quicker.

Typing text then makes the search and a number selects an emoji from the list.

Tho #719 > #720 for sure.

**Comment by carloscuesta** [comment]
Agree let's sort emojis for usage!
