### ISSUE TITLE
Gitmoji in git log

### ISSUE THREAD

**Issue by vhs-dev** [carloscuesta/gitmoji-cli#749]
Hello @carloscuesta!

https://github.com/carloscuesta/gitmoji/issues/597

Issue:

When I run `git log` I don't see emojis.

**OS**: Arch Linux
**gitmoji -v**: 4.7.0
**Node version**: 17.3.0

![gitmoji-cli-gitlog](https://user-images.githubusercontent.com/97140109/149263588-af031efd-c16a-4955-9da8-09700cd8da93.png)

I looked at https://github.com/zetaron/gitmoji-log and it hasn't been updated in 5 years and probably isn't very safe to use due to its age. Would it be better just to use the actual emojis instead of the `:emoji:` reference in the design of this software? Are there any alternatives written in Rust so I don't have to worry as much about my shell being hacked by a rogue NPM dependency?

**Comment by vhs-dev** [comment]
Ah, looks like this one is written in Rust: https://github.com/kegesch/gitmoji-cli

**Comment by vhs-dev** [comment]
I'm going to close this as I don't think it's wise to use NPM for CLI tools and I will uninstall this CLI tool. Thank you!

**Comment by carloscuesta** [comment]
Hey @vhscom 

That's because you're using the `:shortcode:` format there's a configuration option to switch to actual unicode emojis instead of that string:

https://github.com/carloscuesta/gitmoji-cli#options-1
