### ISSUE TITLE
Don't work with Android Studio / IntelliJ

### ISSUE THREAD

**Issue by StefMa** [carloscuesta/gitmoji-cli#76]
Hello @carloscuesta!

The client isn't working in Android Studio (so I think on IntelliJ as well but haven't tested it)

Issue: 
If I run `gitmoji -c` i don't see the emojis.
![bildschirmfoto 2017-10-24 um 13 30 41](https://user-images.githubusercontent.com/10229883/31940777-92534dd4-b8bf-11e7-8f8e-387ddc34afc1.png)

Beside of that I got the same error like in #64 

**OS**: High Sierra
**gitmoji-cli -v**: 1.8.2
**Node version**: v7.10.0

**Comment by carloscuesta** [comment]
Probably the builtin terminal that Android Studio is using, does not provides support for emojis. As you can see, the :zap: is being displayed but not with the Apple Color Emoji Font.
