### ISSUE TITLE
Use pull_request_templates

### ISSUE THREAD

**Issue by jdvala** [carloscuesta/gitmoji-cli#774]
Hello @carloscuesta!

Pretty nice cli tbh, use it daily.

Issue:
No issue just a suggestion, can we use pull_request_template for the first pull request? 

**OS**: OS agnostic
**gitmoji -v**: The new version may be
**Node version**: Does it matter?

**Error Message**:
No error message

**Comment by carloscuesta** [comment]
Hey I'm not sure if I follow you,

What do you mean by using the pull request template for the first commit?

Can you add an example

**Comment by jdvala** [comment]
Sure, sorry to be replying late.

During the first commit on a fresh branch, when user is prompted to enter the commit title, user should also be prompted to add the description for the PR and that description should be adhering or following the pull request template if one is found in the git repo.

I hope this makes it clear.


Another suggestion I have is to use caching and autofill in the commit title and message to the next commit if due to any reason the previous commit fails, be it pre-commit hooks or any other reason for that matter.

**Comment by carloscuesta** [comment]
Thanks for the clarification! Now I understand you;

>  user should also be prompted to add the description for the PR and that description should be adhering or following the pull request template if one is found in the git repo.

From my point of view, this is a bit out of the scope for the `cli`, as the intention is to cover the process of making commits, but not actually open PRs, you have a very nice cli maintained by github that will help you with that https://cli.github.com/

> Another suggestion I have is to use caching and autofill in the commit title and message to the next commit if due to any reason the previous commit fails, be it pre-commit hooks or any other reason for that matter.

This was already was suggested and what we built is the ability to pre-fill the answers for the questions so you can easily retry the command in case of a failure:

```
$ gitmoji -c --title="Commit" --message="Message" --scope="Scope"
```

You can find more info about this in the docs: https://github.com/carloscuesta/gitmoji-cli#options 😊 

Thanks for opening an issue! 🙏🏼
