### ISSUE TITLE
Error while do a commit:  line 3: /dev/tty: No such device or address

### ISSUE THREAD

**Issue by dherediat97** [carloscuesta/gitmoji-cli#78]
Hello @carloscuesta!

The plugin fails when i do a commit (**In Windows**)

Issue: 
Just when i put the pull request number in the gitmojii -c command(i havent pull request in my repository, i dont know if is required).

**OS**: Windows 10
**gitmoji-cli -v**: 1.8.3
**Node version**: 6.9.2

Also, i dont see the emojis, could be a problem in Windows.

**Error Message**: 
ERROR: .git/hooks/prepare-commit-msg: line 3: /dev/tty: No such device or address

![imagen](https://user-images.githubusercontent.com/17063135/32983617-abbc4d52-cc97-11e7-9bfd-190f70cc29f7.png)

Greetings and good job @carloscuesta 👍

**Comment by carloscuesta** [comment]
Hey @dherediat97 

Looks like this is an issue with your environment, see this issue it might help you! https://github.com/atom/atom/issues/8984

**Comment by dherediat97** [comment]
Hello again @carloscuesta , the problem is the environment, because i changed one thing of  [atom/atom#8984](https://github.com/atom/atom/issues/8984) this issue, and now dont work the gpg.

So isnt a problem of your plugin.

Also now i see the emoji icons 👍

**Comment by carloscuesta** [comment]
Closing it then, thanks @dherediat97
