### ISSUE TITLE
Retry after test fail

### ISSUE THREAD

**Issue by stalinkay** [carloscuesta/gitmoji-cli#781]
Hello @carloscuesta!

I write tests for my projects like a lot of other people do. Often times tests fail. Please add an option to retry failed commits after edits.

```
git commit -m "$(cat "$(git rev-parse --git-dir)/COMMIT_EDITMSG)")"
```

**Comment by carloscuesta** [comment]
Hey @stalinkay

Thanks for opening an issue, I think this feature is out of the scope for the cli. The main idea of it is to use emojis on commit messages!

**Comment by stalinkay** [comment]
@carloscuesta Thanks for your quick feedback. I'll do further research on the issue to see if I can manage to working around it from outside Gitmoji.
