### ISSUE TITLE
git-hook doesn't work as expected

### ISSUE THREAD

**Issue by dotterian** [carloscuesta/gitmoji-cli#8]
When i use gitmoji as git-hook it draws first prompt for emoji and then process ends and default git commit procedure starts (text editor opens asking me to enter my commit message, which is blank, or in case if i specify -m "Commit message" it just commits).

![2016-11-23 12-25-53](https://cloud.githubusercontent.com/assets/6250486/20556419/05f50926-b178-11e6-978a-f0072198f534.png)

**Comment by carloscuesta** [comment]
I'm still figuring out how to make the hook work, gitmoji -c works fine

**Comment by dotterian** [comment]
Maybe you should take a look at [gitmoji-commit-hook](https://github.com/welcoMattic/gitmoji-commit-hook) repo in which @welcoMattic already made similar thing?

**Comment by carloscuesta** [comment]
Yes, the base concept of the hook it's from there but the same implementation won't work

**Comment by carloscuesta** [comment]
Hey @dotterian!

I've just fixed this now the commit hook works as expected!

<img width="690" alt="screen shot 2016-11-23 at 22 36 43" src="https://cloud.githubusercontent.com/assets/7629661/20579514/56e4b5e8-b1cd-11e6-9a0a-a258efd44f2b.png">
