### ISSUE TITLE
Backticks in commit messages

### ISSUE THREAD

**Issue by mecha** [carloscuesta/gitmoji-cli#80]
Hello @carloscuesta!

We use backticks ("`") in our commit messages around things like class names, function names etc. However, using backticks in the commit title and description CLI prompts does not appear to be possible, or perhaps I fail to see how it is possible.

**Error Message**: "Enter a valid commit title"

**OS**: Ubuntu 16.04 under WSL
**gitmoji-cli -v**: 1.8.4
**Node version**: 9.2.0

Thanks in advance!

**Edit**:

After creating the issue, I found that this is being explicitly checked for in the [title guard](https://github.com/carloscuesta/gitmoji-cli/blob/master/src/guard.js#L14) and [message guard](https://github.com/carloscuesta/gitmoji-cli/blob/master/src/guard.js#L16). Are there any plans for changing this?
Or rather ... is there anyway I can convince you to change this? :smile:

**Comment by carloscuesta** [comment]
Hey @mecha! 

This was introduced as of #52, I have no problem on removing it but taking in consideration the security

**Comment by CypherPoet** [comment]
I seem to be experiencing this same issue as of `5.0.0`. Reading through the linked issues, it looks like this was intended to be resolved (?) -- but perhaps I'm misinterpreting that.

**Comment by CalinZBaenen** [comment]
I'm now having the same issue on Arch Linux.
