### ISSUE TITLE
gitmoji init won't a the hook if the parent directory does not exists

### ISSUE THREAD

**Issue by dancerphil** [carloscuesta/gitmoji-cli#81]
Hello @carloscuesta!

When run `gitmoji -i`, I got `ERROR: Error: ENOENT: no such file or directory, open 'xxxxxx/.git/hooks/prepare-commit-msg'`

And `gitmoji commit hook created successfully.`

But actually, the hook is not created.

If `/.git/hook` dir not exist, bug happens.

**OS**: macOS Sierra
**gitmoji-cli -v**: 1.8.4
**Node version**: 8.2.1
**Error Message**: 

ERROR: Error: ENOENT: no such file or directory, open '/Users/me/Desktop/g/gitmoji-cli/.git/hooks/prepare-commit-msg'
gitmoji commit hook created successfully.

**Comment by carloscuesta** [comment]
Hey @dancerphil 

As far as I know, it's a standard the hooks directory that lives under `./git/hooks/` when you create a git repo.

On a fresh repository it just works, see

<img width="1440" alt="screen shot 2017-11-21 at 20 14 58" src="https://user-images.githubusercontent.com/7629661/33091985-fece9c80-cef8-11e7-92db-07754289f1f5.png">
