### ISSUE TITLE
gitmoji -c fails with "Use of const in strict mode" at launch time.

### ISSUE THREAD

**Issue by preethikalyani88** [carloscuesta/gitmoji-cli#83]
Hello @carloscuesta!

gitmoji -c fails with "Use of const in strict mode" at launch time.

Issue: 
Description: "gitmoji -c fails with "Use of const in strict mode" at launch time."
The stack trace is as follows:
○ → gitmoji -c

/usr/lib/node_modules/gitmoji-cli/cli.js:4
const meow = require('meow')
^^^^^
SyntaxError: Use of const in strict mode.
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:945:3

The nodejs version is :

○ → node -v
v0.10.48

OS: Amazon Linux 2012

**Error Message**: 

Use of const in strict mode.

**Comment by carloscuesta** [comment]
Hey @preethikalyani88 

This is because you have an unsupported `NODE_VERSION`, as specified in the package.json, the minimum required version of node to use this package is v6 or LTS.

Related #65
