### ISSUE TITLE
Using backtick (`) in commit message isn't valid

### ISSUE THREAD

**Issue by dragid10** [carloscuesta/gitmoji-cli#878]
Hello @carloscuesta!

Issue:
When attempting to use a backtick character (`) like how I would in markdown, gitmoji does not think it is a valid commit

**OS**: MacOS 12,4 (monterey)
**gitmoji -v**: 5.0.2
**Node version**: v18.6.0 (Though I did install via homebrew)

**Error Message**: `>> Enter a valid commit message`

<img width="626" alt="image" src="https://user-images.githubusercontent.com/4042877/179989515-f79c8e57-2c63-4db4-b9be-6c6ab474464c.png">

**Comment by carloscuesta** [comment]
Hey! @dragid10 

Backticks were removed in https://github.com/carloscuesta/gitmoji-cli/issues/52 as it was possible to inject code between them, I'm wondering if we can reconsider this so we can properly escape the commands instead of "banning" the character

**Comment by dragid10** [comment]
Oh wow that actually makes perfect sense, I had no idea of the context. It'd definitely be nice to find some workaround in the future

**Comment by dragid10** [comment]
> Hey @dragid10 do you want to raise a PR to fix this?

I'm more than happy to take a stab at it

**Comment by carloscuesta** [comment]
Hey! I tried to reproduce the injection of `commands` using backticks in git and looks like I'm not able to reproduce it anymore. 

I will remove the guard so `backticks` can be used as part of the message and title again 🙏🏼
