### ISSUE TITLE
gitmoji vs xdg folders

### ISSUE THREAD

**Issue by ccoVeille** [carloscuesta/gitmoji-cli#893]
Hello @carloscuesta!

I would like gitmoji to respect xdg specifications
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

And so store the cache file in `~/home/.cache/gitmoji/` folder.

**Comment by carloscuesta** [comment]
Hey!

I have no plans on implementing this, I’m quite happy with how `conf` handles storing the configuration of the cli.

If you’re not happy with it you can always fork the project and implement it!

In case you have more feature suggestions, please use the provided issue template, thanks 😊

**Comment by ccoVeille** [comment]
> In case you have more feature suggestions, please use the provided issue template, thanks blush

I'm not sure why the template didn't apply.

**Comment by realitymolder** [comment]
> I'm currently implementing no worries

did you manage to implement that?

**Comment by ccoVeille** [comment]
The author refused everything

https://github.com/carloscuesta/gitmoji-cli/pull/894#issuecomment-1211296857
