### ISSUE TITLE
Unable to create `index.lock`: File exists.

### ISSUE THREAD

**Issue by rmngrc** [carloscuesta/gitmoji-cli#9]
Hi Carlos,

First of all thanks for such an amazing piece of cake. I'd be great if I could get this to work but unfortunately I am always getting this error:

![screen shot 2016-11-23 at 12 34 32](https://cloud.githubusercontent.com/assets/1866422/20560372/4b2523fe-b179-11e6-8aff-42f51bb2dee9.png)

I've tried also with `sudo gitmoji -c` but doesn't work either. Any clue of what could be going on here? I've made sure there is no `index.lock` file in my `.git/` folder.

Thank you very much! 

Ramón

**Comment by carloscuesta** [comment]
That's a little bit weird @rmngrc 🤔

Even the file does not exists did you tried to `rm -f .git/index.lock` and then run `gitmoji -c`

**Comment by rmngrc** [comment]
Of course, I did multiple times. I even killed all processes which were using git with no luck :(

**Comment by carloscuesta** [comment]
Did you used the init option? To create the commti hook @rmngrc

**Comment by rmngrc** [comment]
Yes, I did @carloscuesta. I started fresh again so you could see it :)

![screen shot 2016-11-23 at 17 23 19](https://cloud.githubusercontent.com/assets/1866422/20569788/98f43cd2-b1a1-11e6-832a-4514ce311618.png)

**Comment by rmngrc** [comment]
I also realised there is a permission issue when creating the hook:

![screen shot 2016-11-23 at 17 29 05](https://cloud.githubusercontent.com/assets/1866422/20570244/2b015eb0-b1a3-11e6-91d4-5e562a0c65a2.png)

But doing `chmod 755 ./.git/hooks/prepare-commit-msg` didn't fix the issue.

**Comment by carloscuesta** [comment]
Delete the prepare-commit-msg, `gitmoji -c` should be used alone without the -init option.

**Comment by rmngrc** [comment]
Still there... This is so confusing. Anyway, thanks for taking your time to help!!

**Comment by carloscuesta** [comment]
Will try to reproduce this in my local machine.

In the meantime, could you try to clone https://github.com/carloscuesta/gitmoji-cli/tree/test-commit-option branch and tho a npm i && npm link and try if gitmoji -c works?

Thanks!

**Comment by rmngrc** [comment]
Trying your suggestion works. It might be then something related to the repository I work on... will try to have a deep look and figure out what is going on. Maybe some funny permissions within `.git`?

Will keep you posted. Thanks a lot for your quick responses and help!

**Comment by carloscuesta** [comment]
No problem!

What solution worked for you? Deleting the prepare-commit-msg file, or the provided one at the branch?

I do not belive it's a permissions issue, as I said gitmoji -c works without the hook file

Thanks to you too for the feedback! 😊

**Comment by rmngrc** [comment]
Its funny indeed. It works only in new repos but not on the existing ones I have already.

**Comment by vshy108** [comment]
i solved the problem by create and remove the file
`touch .git/index.lock && rm .git/index.lock`
