### ISSUE TITLE
Option `autoAdd` is not working

### ISSUE THREAD

**Issue by KirianCaumes** [carloscuesta/gitmoji-cli#921]
### Describe the bug

The option `autoAdd` from the [documentation](https://github.com/carloscuesta/gitmoji-cli#config) doesn't seems to work when set to `true`: it doesn't run `git add .` and so, new files are not staged.

I tried to put the configuration in the `package.json` or `.gitmojirc.json`, without success.

Maybe I did configure something wrong, but I have no idea what, if that's the case.

I'd be happy to provide more information if needed, thanks for your help 🙏

### Reproduction

Run:
```sh
npm i -g gitmoji-cli #v6.2.0
gitmoji -i
```

Create a new file, for example a `test.txt`.

`package.json`:
```json
{
  "gitmoji": {
    "autoAdd": true,
    "emojiFormat": "emoji",
    "scopePrompt": true,
    "gitmojisUrl": "https://gitmoji.dev/api/gitmojis"
  }
}
```

Create a new commit with `git commit -a` and follow instructions from gitmoji, new files won't be added.

### System Info

```Shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 6.69 GB / 9.73 GB
    Container: Yes
    Shell: Unknown - /bin/sh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by carloscuesta** [comment]
Hey!

The `autoAdd` feature only works when comitting through the cli not through the hook

Thanks for opening the issue 😊

**Comment by KirianCaumes** [comment]
Alright, 

Thanks for lightning fast answer! 

Why it's only available with the CLI? Do you think it might not be useful with the hook? 

I don't know if there's an easy way to implement this.

**Comment by carloscuesta** [comment]
Sure! You can take a look at this for more context:

https://github.com/carloscuesta/gitmoji-cli/issues/168#issuecomment-481866843
