### ISSUE TITLE
Text duplicating in command line when hook applied to "git commit"

### ISSUE THREAD

**Issue by darkylmnx** [carloscuesta/gitmoji-cli#93]
hello @carloscuesta!

So I freshly installed gitmoji, I wanted to use `gitmoji -c` but because of a signing issue a gave up and ended up using the hook on `git commit`.

But, when I did a commit I encountered a visual / graphic bug in the command line. The text keeps duplicating

Issue: 
I did the following :
`gitmoji -i` then `git commit` then I had the options to choose a gitmoji, then I used the "down arrow" and this graphic bug occured

**OS**: Window 10
**gitmoji-cli -v**: 1.8.8
**Node version**: 9.10.0

![image](https://user-images.githubusercontent.com/1426357/38871492-4d6d30e2-4251-11e8-9e67-20c8c0ffee8e.png)

![image](https://user-images.githubusercontent.com/1426357/38871801-188b6b36-4252-11e8-8f20-34fcc209d73e.png)

**Comment by carloscuesta** [comment]
@darkylmnx This is probably an issue with `inquirer-autocomplete-prompt`, i'm updating it to the last version and publishing a new release to see if that fixes the issue.

**Comment by jenewland1999** [comment]
@carloscuesta This is still very much an issue with `gitmoji-cli` v3.2.12 and `node` v15.2.1. Using the example on the `inquirer-autocomplete-prompt` repo it doesn't appear to have any issues on Windows. It only seems to relate to the git hook. Perhaps there is something specific to how code around the hook works as opposed to executing it through `gitmoji -c`

Here's a demo:

![6w4VOCd24x](https://user-images.githubusercontent.com/34895363/99915624-ac5ba500-2cfc-11eb-8c8b-5c1bad2c7fa2.gif)

**Comment by jenewland1999** [comment]
I'm more than happy to help troubleshoot this issue further if you want to try anything just let me know. I will perhaps be able to look into this more when I have more time on my hands.

**Comment by carloscuesta** [comment]
@jenewland1999 I do not own a Windows machine so it's very difficult for me to debug this.

If anyone who uses Windows is up on investigating this feel free to open a PR
