### ISSUE TITLE
Commit message character count/limits or Vim support?

### ISSUE THREAD

**Issue by StagasaurusRex** [carloscuesta/gitmoji-cli#94]
I am trying to enforce a hard limit on commit title length (just for myself) and I think it would be helpful to have some indication of how many characters you've typed so far or a configurable hard limit on how many characters the title is.

Vim (or at least my vim), does this nicely by changing color after a certain number of characters.
![screen shot 2018-04-28 at 11 45 28 pm](https://user-images.githubusercontent.com/4968936/39403311-4217899a-4b3e-11e8-892e-57b584869292.png)

Otherwise a simple x/50 would work.

Alternatively a more general approach, might be to allow the user to enter the commit message and title in their default editor like git does.

Thoughts?

**Comment by carloscuesta** [comment]
Related with #96
