### ISSUE TITLE
Emoji 🎨 is automatically added with `npm version x.x.x`

### ISSUE THREAD

**Issue by KirianCaumes** [carloscuesta/gitmoji-cli#946]
### Describe the bug

When I run the `npm version x.x.x` command while using the gitmoji hook, a "🎨" is automatically added to my commit message.

Is it a default fallback emoji? Is there a way to to not add it with the `npm version x.x.x` command?

Maybe, some kind of exception can be done to to disable gitmoji hook on this command?

### Reproduction

```sh
npm version -m "test %s" 1.0.0
# Commit message: 🎨 test 2.0.0
```

### System Info

```Shell
System:
    OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 4.91 GB / 9.73 GB
    Container: Yes
    Shell: Unknown - /bin/sh
  Binaries:
    Node: 18.11.0 - /usr/bin/node
    npm: 8.19.2 - /usr/bin/npm
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by carloscuesta** [comment]
Hey! 

I'm not able to reproduce the behaviour described 😓 in macOS 

The 🎨 emoji is actually the first one on the list. I was checking npm docs and found `version` ships an [option to ignore the hooks](https://docs.npmjs.com/cli/v8/commands/npm-version#commit-hooks):

```
npm version --no-commit-hooks
```

That should do the trick 👍🏼

**Comment by KirianCaumes** [comment]
Hey, thanks for your answer!

It doesn't seems to sove my problem, maybe it's more deep than I tought (or I'm not awake enough yet 😴).

Here is more context: 

I have a git project with two folders/projects inside: `back` and `front`. Both containing `package.json` plus another at the root folder. I'm also using of course the `gitmoji-cli` hook.

I have create a custom command to run the `npm version` on the three `package.json`:

```json
// /package.json
{
    "version": "2.0.1",
    "scripts": {
        // ...
        "preversion": "git add .",
        "tag": "(cd front && npm version --no-commit-hooks \"$npm_config_to\") && (cd back && npm version --no-commit-hooks \"$npm_config_to\") && npm version --no-commit-hooks --force -m \"🔖 %s\" \"$npm_config_to\"",
        "postversion": "git push && git push --tags"
    },
    "gitmoji": {
        "autoAdd": false,
        "emojiFormat": "emoji",
        "scopePrompt": true,
        "gitmojisUrl": "https://gitmoji.dev/api/gitmojis"
    }
}
```

So, when I run `npm run tag --to=2.0.1`, it updates everything, create commit and push commit/tag.

But the commit message looks like that: `🎨 🔖 2.0.1`.

Maybe, I can disable the `gitmoji-cli` hook in the `preversion` and enable it again in the `postversion`, but I'm not a huge fan of this workaround.

**Comment by carloscuesta** [comment]
Hey! Can you try:

```
--commit-hooks=false
```

The flag should prevent the hook from running 🤔

**Comment by KirianCaumes** [comment]
Hi again!

It doesn't seems to be working either 😕

I have created a [respository](https://github.com/KirianCaumes/gitmoji-npmversion-bug) to test the issue. It come with a devcontainer, so we can be sure that the environment is the same. There's also instructions about the "npm version" command that I use.

Let me know if I can provide more elements or test other ideas!

**Comment by carloscuesta** [comment]
Hey @KirianCaumes I tried with your test repository and I'm unable to reproduce the issue, 

<img width="1142" alt="Screenshot 2023-01-03 at 12 41 57" src="https://user-images.githubusercontent.com/7629661/210350744-8221c1ee-9676-4054-9a15-beaf326dfed7.png">

<img width="1172" alt="Screenshot 2023-01-03 at 12 41 09" src="https://user-images.githubusercontent.com/7629661/210350731-f8c3b182-e6b7-4cb4-9614-2efe92d15a1e.png">

From the cli side, we're not setting any gitmoji as default in the first prompt:

https://github.com/carloscuesta/gitmoji-cli/blob/7539028927fa489a484845eaa3b4c78c9d1884dc/src/commands/commit/prompts.js#L36-L48

The only difference I can spot between our environments is the operating system, I'm using macOS and I unfortunately don't have an ubuntu machine to test so I won't be able to troubleshoot this issue further!

If you want to help you can clone the repository and try debugging it with the build command and running the build locally:

https://github.com/carloscuesta/gitmoji-cli/blob/7539028927fa489a484845eaa3b4c78c9d1884dc/package.json#L16

```bash
node ./lib/cli.js
```

Thanks! 🙏🏼
