### ISSUE TITLE
Should Be Refactored Command gitmoji -c

### ISSUE THREAD

**Issue by aldairandre** [carloscuesta/gitmoji-cli#948]
### Discussion

Hey guys, I'm sure everyone here loves Gitmoji, who doesn't!
Let's get to the actual discussion, first sorry for my bad english.
But don't you think the gitmoji -c command should be refactored?
Why am I saying this....
[Little history]
Today I was working on a small project and editing 3 different files, at some point in my work I decided to send only one file with "gitmoji -c", to my surprise what happened was that the other 2 files I was working on were also committed.
Now my point is, folks, don't you guys think the gitmoji -c command should be refactored to just commit only the files that are in the git state area?

Sorry for opening an issue in the wrong rep 😂

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue requesting the same feature.

**Comment by carloscuesta** [comment]
Hey!

You can disable this behaviour by using the configuration command:

👉🏼 https://github.com/carloscuesta/gitmoji-cli#config

Read more about it in the docs 📝
