### ISSUE TITLE
Refer to issues using keywords or in a different repository

### ISSUE THREAD

**Issue by mateusvelleda** [carloscuesta/gitmoji-cli#95]
Hello @carloscuesta!

It's not possible to refer to issues using keywords or refer to issues in a different repository.

Issue: 
It's common to have issues assigned to a team's repository instead of to the project's one. By using gitmoji I can't use keywords to automatically close issues when my PR's get accepted and merged.
By refer using keywords I mean something like `closes carloscuesta/gitmoji-cli#94` or even `closes #94`
To better understand this issue, you can take a look at https://help.github.com/articles/closing-issues-using-keywords/
I'm sorry if it's a misuse from my side.

**Mac OS**:
**gitmoji-cli 1.8.8**:
**Node version 8.10.0**:

When I try to do so, I get this:
**>> Enter the number of the reference without the #. Eg: 12**:

**Comment by mateusvelleda** [comment]
Hey @carloscuesta 

I just realized it's just a matter of editing the commit message, adding my keywords so.
Even so, I'll keep this issue open as a suggestion of _PR reference_ improvement.

Thanks,

**Comment by carloscuesta** [comment]
Hello @mateusvelleda,

The issue referencing now is a little bit weird if you're not used to this cli so I will consider this as a feature request and try to improve it!
