### ISSUE TITLE
Automatically apply 50/72 rule (max characters on commit title/message lines)

### ISSUE THREAD

**Issue by erikhuizinga** [carloscuesta/gitmoji-cli#96]
Hello @carloscuesta!

Automatically apply (or add a (default) option to apply) the 50/72 line length rule of commit titles/messages.

Issue: 
I sometimes write (too) long commit titles and messages. To prevent this, I use a text editor and I keep a look out for the line length:

 - The title is at most 50 characters long.
 - The rest of the commit message's lines are at most 72 characters long.

This is known as the 50/72 rule, which AFAIK is general and good practice. It plays nicely on GitHub (try committing and pushing a very long commit title: GitHub ellipsizes title and wraps the rest into the message, which beats the purpose of a commit title summarising your commit).

I think it would be really nice if three things would happen in `gitmoji-cli`:

1. `gitmoji -c` somehow indicates where the 50th character is. This allows the user to see how much title they have left.
1. `gitmoji-cli` warns the user if the title is too long, but allows it if the user decides to create a longer title.
1. `gitmoji-cli` automatically wraps lines of the commit message, so that the user needs not think about the 72 rule. This would allow the user to simply type sentences and gitmoji does the rest. Line breaks should replace every last space character on or before the 73rd character of a line. Too long words (i.e. over 72 characters, e.g. URLs not containing spaces) simply cannot be broken into multiple lines, so gitmoji should do the line break directly after such a word.

**OS**: this issue is unrelated to any OS
**`gitmoji-cli -v`**: `1.8.8`
**`node -v`**: `v10.0.0`

**Error Message**:  N/A

**Screenshot**: As an example, my default commit message has helper lines (comments) that indicate where the 50th and 72nd columns are. Such a helper line could be used for the `gitmoji -c` title, either above, on or under where the user types.

<img width="752" alt="schermafbeelding 2018-05-03 om 19 05 51" src="https://user-images.githubusercontent.com/19374736/39591780-12605702-4f05-11e8-8a25-8c5694a8f3a7.png">

**Comment by carloscuesta** [comment]
@erikhuizinga I'm not really a fan of automatically enforcing practices, but for me makes sense to add the counter or something like that in order to help users to follow the 50/72 rule 👍

**Comment by carloscuesta** [comment]
Related with #94
