### ISSUE TITLE
Only log successful update if gitmojis changed

### ISSUE THREAD

**Issue by erikhuizinga** [carloscuesta/gitmoji-cli#97]
The following always logs a successful update, but how do I know if there were any gitmojis updated? As a user I want to know about new or changed gitmojis, so I can use them properly.

https://github.com/carloscuesta/gitmoji-cli/blob/b5e81392c53b42ab615379777c8a4a3f31ce4dcd/src/gitmoji.js#L188

More awesome would be an automatic update after a gitmoji-cli update. And even more awesome would be a short summary of changed and new gitmojis.

**Comment by A1rPun** [comment]
I think you have the following options:

- Keep track of a `CHANGELOG.md` in the `gitmoji` repo. Users can track which entries have been added or changed.
- Add a `version` property to every entry and add them to `gitmoji -l`. Not ideal when dealing with changed entries.
- Drop `gitmoji -u` entirely and let users update with `npm i (-g) gitmoji-cli`. This will radically discard any issues about the update feature (No disrespect on your clever caching mechanism and this great issue).
- Last but not least, this great tool is all about using great commit messages. I think a cool way to interact with the results of `gitmoji-cli` is to let users check the commits of [`gitmoji`](https://github.com/carloscuesta/gitmoji/commits/master)! It will be self-documenting and self-referential. You only have to look at the sparkles :sparkles::sparkles::sparkles::sparkles: :heart_eyes:
