### ISSUE TITLE
Error on exec gitmoji-cli

### ISSUE THREAD

**Issue by brunorq** [carloscuesta/gitmoji-cli#974]
### Describe the bug

I am getting an error message when using the `gitmoji -c` command. A few days ago it worked correctly, but for some reason it is broken.

![image](https://user-images.githubusercontent.com/23287948/205777878-8e72cd72-445b-4394-a2a3-eb359205d521.png)

running on zsh with p10k

![image](https://user-images.githubusercontent.com/23287948/205778161-4c42dfa3-651b-457c-a444-fd79eaf14811.png)

i can't run gitmoji version, output is this errors on first image.

### Reproduction

Run `gitmoji -c`

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 AMD FX(tm)-4300 Quad-Core Processor
    Memory: 3.71 GB / 7.76 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 12.22.9 - /usr/bin/node
    npm: 8.5.1 - /usr/bin/npm
  Browsers:
    Chromium: 108.0.5359.71
    Firefox: 107.0.1
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by carloscuesta** [comment]
Hey!

The minimum node version is:

https://github.com/carloscuesta/gitmoji-cli/blob/314e03eb402b8f5967448d5136c0f7a08364eb30/package.json#L7

Thanks!
