### ISSUE TITLE
not tty

### ISSUE THREAD

**Issue by coder-pig** [carloscuesta/gitmoji-cli#98]
Hello @carloscuesta!

When i use gitmoji-cli，console print:

![image](https://user-images.githubusercontent.com/6879486/40871415-ce094caa-666d-11e8-9f00-d2a834712e48.png)

**OS**: windows 10
**gitmoji-cli -v**:1.8.9
**Node version**:10.3.0

How can fix it？ths~

**Comment by carloscuesta** [comment]
Thisvis an issue relatef with your machine configuration of gpg when signing commits, not gitmoji-cli
